#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
# Builds the four FHE programs against a built niobium-client (the FHE-dev image has it at /opt/niobium-client).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
# Default: the FHE-dev image's /opt/niobium-client, else a native checkout next to this app folder.
NC="${NIOBIUM_CLIENT_DIR:-/opt/niobium-client}"
if [ -z "${NIOBIUM_CLIENT_DIR:-}" ] && [ ! -d "$NC" ] && [ -d "$ROOT/../niobium-client/vendor/lib" ]; then
  NC="$(cd "$ROOT/../niobium-client" && pwd)"
fi
[ -d "$NC/vendor/lib/niobium-client" ] || { echo "niobium-client SDK not found at $NC; set NIOBIUM_CLIENT_DIR"; exit 1; }
echo "using niobium-client at $NC"
GEN=(); command -v ninja >/dev/null && GEN=(-G Ninja)
cmake -S "$ROOT/app" -B "$ROOT/build" ${GEN[@]+"${GEN[@]}"} -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_PREFIX_PATH="$NC/vendor/lib/niobium-client;$NC/vendor/lib/openfhe"
cmake --build "$ROOT/build" -j"${BUILD_JOBS:-2}"
echo "built: $(ls "$ROOT"/build/era_* | xargs -n1 basename | tr '\n' ' ')"
