# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
# Local targets need no Fog account. `make fog-ready` checks the Fog prerequisites without contacting anything.
.PHONY: build venv twin test unit services check demo demo-cpu fog-ready clean
build:
	./build.sh
venv:
	[ -x .venv/bin/python ] || python3 -m venv .venv
	.venv/bin/pip install -q -r requirements-dev.txt
twin: venv
	.venv/bin/python tools/twin.py sweep
test: build
	NREC=25 ./run_test.sh --cpu
	NREC=25 ./run_test.sh --sim
	NREC=25 ./run_test.sh --sim-full
unit:
	python3 -m unittest discover -s tests -v
services: venv
	tests/test_services.sh
check: test unit services
demo:
	./start_local.sh sim
demo-cpu:
	./start_local.sh cpu
fog-ready:
	fog --selftest >/dev/null 2>&1 && echo "fog CLI selftest OK (offline)"
	python3 services/compute_service.py --backend fog --preflight
clean:
	rm -rf build/ run_cpu/ run_sim/ run_sim-full/ run_fog/ run_demo/ client_home/ server_home/
	rm -rf era_server_workload_*/ nbcc_fhetch_replay_source_*/
