#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
set -euo pipefail

usage() {
  cat <<'EOF'
run_test.sh — Which Era Are You?: keygen -> encrypt -> server -> decrypt, then compare to the faithful twin.
Usage: ./run_test.sh [--cpu | --sim | --sim-full | -h]
  (no flag)   dispatch the server to the Niobium Fog (default; records hollow; needs a Fog API key)
  --cpu       plain-OpenFHE local validation
  --sim       hollow record -> local fhetch_sim replay -> twin compare (a local rehearsal of the Fog run)
  --sim-full  real-math record -> replay + ring-level ciphertext-identity check vs OpenFHE
Env: FOG_TARGET (default FOG; FUNC_SIM = hardware-free simulator on the Fog)
     RECORD     which twin case to score (default 0)
     NREC       validation-sweep size, max 25 (default 1). NREC>1 reuses one key set: a test shortcut.
     RING_DIM + RINGCHK=--no-ring-dim-check   local-only testing of a smaller ring
EOF
}

MODE="fog"; FLAG=""; SIMFULL=0
case "${1:-}" in
  --cpu) MODE="cpu"; FLAG="--cpu";;
  --sim) MODE="sim";;
  --sim-full) MODE="sim"; SIMFULL=1;;
  "") MODE="fog";;
  -h|--help) usage; exit 0;;
  *) usage; exit 2;;
esac

FOG_TARGET="${FOG_TARGET:-FOG}"
RINGCHK="${RINGCHK:-}"
RING_DIM="${RING_DIM:-65536}"
HOLLOW_FLAG=""
case "$MODE" in
  fog) HOLLOW_FLAG="--hollow";;
  sim) [ "$SIMFULL" = 1 ] || HOLLOW_FLAG="--hollow";;
esac
RECORD="${RECORD:-0}"
NREC="${NREC:-1}"

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/build"; RUN="$ROOT/run_${MODE}"; [ "$SIMFULL" = 1 ] && RUN="$ROOT/run_sim-full"
CLIENT="$RUN/client_home"; SERVER="$RUN/server_home"
rm -rf "$RUN"; mkdir -p "$CLIENT" "$SERVER"
[ -x "$BUILD/era_server" ] || { echo "Build first: ./build.sh"; exit 1; }

now() { python3 -c 'import time;print(time.time())'; }
T0=$(now)

# 1. keygen writes ALL keys into the client home
"$BUILD/era_keygen" "$CLIENT" "$RING_DIM" > "$RUN/keygen.json"
T1=$(now)

# 2. provision the server home: crypto context, rotation keys, plaintext era profiles. NO secret key
#    (and no public key either: era_server never reads it).
cp "$CLIENT/cc.bin" "$CLIENT/rk.bin" "$SERVER/"
cp "$ROOT/data/eras.csv" "$SERVER/"
[ ! -f "$SERVER/sk.bin" ] || { echo "[FATAL] secret key in server home"; exit 1; }

# 3. negative test: the server must refuse to start with a secret key in its home
cp "$CLIENT/sk.bin" "$SERVER/sk.bin"
if (cd "$RUN" && "$BUILD/era_server" "$SERVER" --cpu $RINGCHK >/dev/null 2>&1); then
  echo "[FATAL] server started with a secret key present"; exit 1
fi
rm -f "$SERVER/sk.bin"; echo "negative test: server refused a planted secret key"

# 4. Fog mode: preflight for an API key; with a key present the `fog submit` dispatch below is mandatory
if [ "$MODE" = "fog" ] && [ ! -f "${FOG_HOME:-$HOME/.fog}/credentials" ] && [ -z "${FOG_API_TOKEN:-}" ]; then
  echo "No Fog API key found, so nothing was dispatched."
  echo "  Sign in:  fog login        Sign up:  https://console.niobium.co/request-account"
  echo "  Account-free local validation:  ./run_test.sh --sim"
  exit 0
fi

# 5. encrypt -> server -> decrypt, one quiz taker per record (per-record packing)
[ "$NREC" -gt 1 ] && echo "validation sweep: $NREC records under ONE key set (test shortcut; the app uses fresh keys per client)"
: > "$RUN/decrypted.jsonl"
ENC_MS=0; SRV_MS=0; DEC_MS=0; PEAK_KB=0
for ((i=0; i<NREC; i++)); do
  idx=$((RECORD + i))
  U=$(python3 -c "import json,sys;c=json.load(open('$ROOT/data/twin_cases.json'))[$idx];print(','.join(repr(x) for x in c['u']))")
  a=$(now); printf '%s\n' "$U" | "$BUILD/era_encrypt" "$CLIENT" "$CLIENT/ct_query_$i.bin" >/dev/null; b=$(now)   # plaintext via stdin, not argv
  cp "$CLIENT/ct_query_$i.bin" "$SERVER/ct_query.bin"              # only ciphertext crosses
  rm -rf "$RUN"/era_server_workload_*                               # fresh trace for fresh inputs
  if [ "$MODE" = "fog" ]; then
    # THE DEFAULT PATH: the server runs under `fog submit`. Niobium documents that the Fog runs exactly N = 2^16, and the
    # ring-dim guard stays on (RINGCHK is never forwarded here).
    (cd "$RUN" && fog submit "$BUILD/era_server" "$SERVER" $HOLLOW_FLAG --target="$FOG_TARGET") > "$RUN/server_$i.log" 2>&1 \
      || { cat "$RUN/server_$i.log"; exit 1; }
  else
    python3 - "$RUN" "$BUILD/era_server" "$SERVER" $FLAG $HOLLOW_FLAG $RINGCHK > "$RUN/server_$i.log" 2>&1 <<'PY' || { cat "$RUN/server_$i.log"; exit 1; }
import resource, subprocess, sys
r = subprocess.run(sys.argv[2:], cwd=sys.argv[1])
rss = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss
print(f"PEAK_RSS_KB={rss // 1024 if sys.platform == 'darwin' else rss}")  # macOS reports bytes, Linux KB
sys.exit(r.returncode)
PY
    kb=$(grep -o 'PEAK_RSS_KB=[0-9]*' "$RUN/server_$i.log" | cut -d= -f2); [ "$kb" -gt "$PEAK_KB" ] && PEAK_KB=$kb
  fi
  c=$(now)
  cp "$SERVER/ct_result.bin" "$CLIENT/ct_result_$i.bin"
  "$BUILD/era_decrypt" "$CLIENT" "$CLIENT/ct_result_$i.bin" >> "$RUN/decrypted.jsonl"; d=$(now)
  ENC_MS=$(python3 -c "print($ENC_MS+($b-$a)*1000)"); SRV_MS=$(python3 -c "print($SRV_MS+($c-$b)*1000)"); DEC_MS=$(python3 -c "print($DEC_MS+($d-$c)*1000)")
done
grep -h "ring-level identity" "$RUN"/server_*.log | head -1 || true

# 6. report
echo ""
LABEL="$MODE"; [ "$SIMFULL" = 1 ] && LABEL="sim-full, real-math record"; [ -n "$HOLLOW_FLAG" ] && LABEL="$MODE, hollow record"
echo "=== Which Era Are You? ($LABEL) ==="
if [ "$RECORD" = 0 ]; then python3 "$ROOT/tools/compare.py" "$RUN/decrypted.jsonl" "$NREC"; STATUS=$?
else echo "  (RECORD != 0: twin comparison indexes from 0; skipped)"; STATUS=0; fi
sz() { python3 -c "import os;print(f'{os.path.getsize(\"$1\")/1e6:.2f} MB')"; }
echo "  deployment profile:"
echo "    keys (one-time setup, client -> server): crypto context $(python3 -c "import os;print(os.path.getsize(\"$CLIENT/cc.bin\"))") B, rotation keys $(sz "$CLIENT/rk.bin")"
echo "    per quiz: query ciphertext $(sz "$CLIENT/ct_query_0.bin") up, result ciphertext $(sz "$CLIENT/ct_result_0.bin") down"
python3 -c "print(f'    time: keygen {($T1-$T0)*1000:.0f} ms, encrypt {$ENC_MS/$NREC:.0f} ms, server {$SRV_MS/$NREC:.0f} ms, decrypt {$DEC_MS/$NREC:.0f} ms (per record)')"
[ "$MODE" != fog ] && echo "    peak server memory: $((PEAK_KB/1024)) MB"
exit $STATUS
