#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
# Runs both services as two local processes (no Docker). Needs ./build.sh done first.
#   ./start_local.sh [cpu|sim|sim-full|fog]      (default: $ERA_BACKEND, else sim)
# Env: PORT (quiz page, default 8000), COMPUTE_PORT (default 8001), FOG_TARGET (fog only; default FOG)
set -euo pipefail
cd "$(dirname "$0")"
BACKEND="${1:-${ERA_BACKEND:-sim}}"
PORT="${PORT:-8000}"; COMPUTE_PORT="${COMPUTE_PORT:-8001}"

# Fail fast, before any keys are made, if the backend can't run here (e.g. fog without `fog login`).
python3 services/compute_service.py --backend "$BACKEND" --preflight

for p in "$PORT" "$COMPUTE_PORT"; do
  if lsof -nP -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Port $p is already in use (is the demo already running?). Stop it, or pick another: PORT=8010 COMPUTE_PORT=8011 $0 $BACKEND"
    exit 1
  fi
done

python3 services/compute_service.py --backend "$BACKEND" --port "$COMPUTE_PORT" & CPID=$!
trap 'kill $CPID 2>/dev/null' EXIT
python3 services/client_service.py --port "$PORT" --compute "http://127.0.0.1:$COMPUTE_PORT"
