# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Unit tests for the compute backend layer. Stdlib only; contacts no network service.

  python3 -m unittest discover -s tests -v
"""
import os
import re
import sys
import tempfile
import unittest
from unittest import mock

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "services"))
import backends  # noqa: E402

BUILD = os.path.join(ROOT, "build")
SERVER = os.path.join(BUILD, "era_server")


class Commands(unittest.TestCase):
    def test_every_backend_runs_the_same_server_binary(self):
        for name in backends.BACKENDS:
            cmd = backends.get(name, BUILD).command("/job")
            self.assertIn(SERVER, cmd, name)
            self.assertIn("/job", cmd, name)

    def test_local_commands(self):
        self.assertEqual(backends.get("cpu", BUILD).command("/j"), [SERVER, "/j", "--cpu"])
        self.assertEqual(backends.get("sim", BUILD).command("/j"), [SERVER, "/j", "--hollow"])
        self.assertEqual(backends.get("sim-full", BUILD).command("/j"), [SERVER, "/j"])

    def test_fog_command_is_the_documented_submit(self):
        self.assertEqual(backends.get("fog", BUILD, target="FUNC_SIM").command("/j"),
                         ["fog", "submit", SERVER, "/j", "--hollow", "--target=FUNC_SIM"])

    def test_fog_target_defaults_to_real_fog_and_follows_env(self):
        with mock.patch.dict(os.environ, {}, clear=False):
            os.environ.pop("FOG_TARGET", None)
            self.assertEqual(backends.get("fog", BUILD).target, "FOG")
            os.environ["FOG_TARGET"] = "FUNC_SIM"
            self.assertEqual(backends.get("fog", BUILD).target, "FUNC_SIM")

    def test_fog_never_bypasses_ring_dim_guard(self):
        self.assertNotIn("--no-ring-dim-check", backends.get("fog", BUILD).command("/j"))

    def test_hollow_backends_pass_hollow_and_only_they_do(self):
        """The Fog (and its local rehearsal, sim) must record WITHOUT real math: --hollow on the command
        line, and `hollow = True` so the compute service can check era_server's reported mode."""
        for name in backends.BACKENDS:
            b = backends.get(name, BUILD)
            self.assertEqual("--hollow" in b.command("/j"), b.hollow, name)
        self.assertTrue(backends.get("fog", BUILD).hollow)
        self.assertTrue(backends.get("sim", BUILD).hollow)
        self.assertFalse(backends.get("sim-full", BUILD).hollow, "sim-full needs real math for the ring check")
        self.assertFalse(backends.get("cpu", BUILD).hollow)

    def test_every_remote_backend_is_hollow(self):
        for name in backends.BACKENDS:
            b = backends.get(name, BUILD)
            if b.remote:
                self.assertTrue(b.hollow, f"{name} sends a trace off this machine; it must be hollow")

    def test_unknown_backend(self):
        with self.assertRaises(ValueError):
            backends.get("gpu", BUILD)


class Describe(unittest.TestCase):
    KEYS = {"id", "short", "name", "detail", "where", "remote"}

    def test_every_backend_describes_itself_for_the_ui(self):
        for name in backends.BACKENDS:
            d = backends.get(name, BUILD).describe()
            self.assertTrue(self.KEYS <= set(d), name)
            self.assertEqual(d["id"], name)
            self.assertNotRegex(d["name"] + d["detail"], r"[<>]", "descriptions are plain text")

    def test_only_fog_is_remote(self):
        remote = {n for n in backends.BACKENDS if backends.get(n, BUILD).describe()["remote"]}
        self.assertEqual(remote, {"fog"})


class Parse(unittest.TestCase):
    def test_fog_job_id_from_fog_submit_output(self):
        # Line format from niobium-client scripts/fog: print(f"[fog] assigned {jid} -> {server}")
        err = "[fog] queued as j-123; long-polling for a worker…\n[fog] assigned j-123 -> https://w/jobs/j-123/run\n"
        self.assertEqual(backends.get("fog", BUILD).parse("", err)["fog_job"], "j-123")

    def test_local_backends_report_no_transport(self):
        for name in ("cpu", "sim", "sim-full"):
            self.assertIsNone(backends.get(name, BUILD).parse("", "")["transport_ms"], name)

    # A Fog run as the compute service sees it: (ms since launch, stderr line). Line formats from
    # niobium-client scripts/fog, src/fhetch_transport/client.cpp and app/server.cpp.
    FOG_TIMELINE = [
        (5, "[fog] POST https://api.niobium.co/jobs/ {mode:batch, target:FOG}"),
        (1200, "[fog] assigned j-123 -> https://w/jobs/j-123/run"),
        (1201, "[fog] exec /b/era_server /j --hollow --target=FOG"),
        (2500, "[server] received 2098221 bytes of ciphertext (no key to open it)"),
        (3000, "[fog] upload 0/20 MB (0%)"),
        (6000, "[fog] upload 10/20 MB (50%)"),
        (9000, "[fog] upload 20/20 MB (100%)"),
        (9001, "[fog] upload complete — replaying on target FOG, waiting for the server"),
        (13500, "[server] replay done in 10500.2 ms"),
        (13600, "[server] returned 1049627 bytes, still encrypted (compressed to 1 RNS tower)"),
    ]
    FOG_STDOUT = "[nbcc_fhetch_replay] POSTing 20971520 bytes (streamed, project=x, target=FOG) → https://w/jobs/j-123/run\n"

    def test_fog_transport_timing_from_the_timeline(self):
        meta = backends.get("fog", BUILD).parse(self.FOG_STDOUT, "\n".join(l for _, l in self.FOG_TIMELINE), self.FOG_TIMELINE)
        self.assertEqual(meta["fog_job"], "j-123")
        self.assertEqual(meta["fog_queue_ms"], 1200)
        self.assertEqual(meta["upload_ms"], 6001)            # first progress line -> "upload complete"
        self.assertEqual(meta["upload_bytes"], 20971520)
        self.assertEqual(meta["fog_wait_ms"], 4499)          # "upload complete" -> replay() returned
        self.assertEqual(meta["transport_ms"], meta["upload_ms"])
        self.assertIsNone(meta["download_ms"], "the transport client does not report it yet")

    def test_fog_timing_degrades_to_none_when_lines_are_missing(self):
        meta = backends.get("fog", BUILD).parse("", "[fog] assigned j-1 -> u\n", [(10, "[fog] assigned j-1 -> u")])
        self.assertEqual(meta["fog_job"], "j-1")
        self.assertEqual(meta["fog_queue_ms"], 10)
        for k in ("upload_ms", "upload_bytes", "fog_wait_ms", "transport_ms", "download_ms"):
            self.assertIsNone(meta[k], k)

    def test_ring_check_detected(self):
        err = "[server] ring-level identity check: replay == OpenFHE, bit for bit\n"
        self.assertTrue(backends.get("sim-full", BUILD).parse("", err)["ring_check"])
        self.assertFalse(backends.get("sim", BUILD).parse("", "")["ring_check"])


class FogPreflight(unittest.TestCase):
    """The Fog preflight must explain what's missing without contacting anything."""

    def _env(self, fog_home, token=None):
        env = {"FOG_HOME": fog_home}
        if token:
            env["FOG_API_TOKEN"] = token
        return env

    def test_no_credentials_is_reported_with_the_fix(self):
        with tempfile.TemporaryDirectory() as d, mock.patch.dict(os.environ, self._env(d)):
            os.environ.pop("FOG_API_TOKEN", None)
            with self.assertRaises(backends.BackendUnavailable) as cm:
                backends.get("fog", BUILD).preflight()
            text = " ".join(w + " " + f for w, f in cm.exception.problems)
            self.assertIn("fog login", text)
            self.assertIn("request-account", text)

    def test_credentials_file_or_token_is_enough_offline(self):
        with tempfile.TemporaryDirectory() as d:
            open(os.path.join(d, "credentials"), "w").close()
            with mock.patch.dict(os.environ, self._env(d)), \
                 mock.patch("shutil.which", return_value="/usr/bin/true"):
                backends.get("fog", BUILD).preflight()          # no raise, nothing contacted
        with tempfile.TemporaryDirectory() as d, \
             mock.patch.dict(os.environ, self._env(d, token="t")), \
             mock.patch("shutil.which", return_value="/usr/bin/true"):
            backends.get("fog", BUILD).preflight()

    def test_missing_cli_is_reported(self):
        with tempfile.TemporaryDirectory() as d, mock.patch.dict(os.environ, self._env(d, token="t")), \
             mock.patch("shutil.which", return_value=None):
            with self.assertRaises(backends.BackendUnavailable) as cm:
                backends.get("fog", BUILD).preflight()
            self.assertTrue(any("fog" in w for w, _ in cm.exception.problems))


class UiIsBackendAgnostic(unittest.TestCase):
    def test_web_ui_never_branches_on_a_backend_id(self):
        with open(os.path.join(ROOT, "web", "app.js")) as f:
            js = f.read()
        for name in backends.BACKENDS:
            self.assertIsNone(re.search(rf"""["'`]{re.escape(name)}["'`]""", js),
                              f"web/app.js mentions backend id {name!r}; use meta.backend instead")


if __name__ == "__main__":
    unittest.main()
