#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
# Live two-process test of the demo for each LOCAL backend (no Fog account needed):
#   quizzes through the real services vs the twin, backend self-description, compute-restart
#   self-heal, and the no-secret-key guards. Uses side ports so it never collides with a running demo.
#   tests/test_services.sh [backend ...]        (default: cpu sim sim-full)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
PY="${PY:-$ROOT/.venv/bin/python}"; [ -x "$PY" ] || { echo "run 'make venv' first (the twin needs numpy)"; exit 1; }
CP=8101; UP=8100; C="http://127.0.0.1:$CP"; U="http://127.0.0.1:$UP"
TMP="$(mktemp -d)"; CPID=""; UPID=""
cleanup() { kill $CPID $UPID 2>/dev/null || true; wait 2>/dev/null || true; rm -rf "$TMP"; }
trap cleanup EXIT
fail() { echo "FAIL: $*"; echo "--- compute log"; tail -20 "$TMP/compute.log" || true; echo "--- client log"; tail -20 "$TMP/client.log" || true; exit 1; }
wait_url() { for _ in $(seq 1 120); do curl -sf "$1" >/dev/null 2>&1 && return 0; sleep 0.5; done; return 1; }
start_compute() { python3 services/compute_service.py --backend "$1" --port $CP --home "$TMP/server_home" >> "$TMP/compute.log" 2>&1 & CPID=$!; wait_url "$C/v1/health" || fail "compute did not start"; }

for B in "${@:-cpu sim sim-full}"; do
  for B1 in $B; do
    echo "== backend $B1"
    rm -rf "$TMP"/*; : > "$TMP/compute.log"
    start_compute "$B1"
    python3 services/client_service.py --port $UP --compute "$C" --home "$TMP/client_home" > "$TMP/client.log" 2>&1 & UPID=$!
    wait_url "$U/api/status" || fail "client did not start"

    # the backend describes itself; the page renders it
    got=$(curl -s "$U/api/status" | python3 -c "import json,sys;print(json.load(sys.stdin)['compute']['backend']['id'])")
    [ "$got" = "$B1" ] || fail "status reports backend $got"
    curl -sf "$U/" | grep -q "Which" || fail "quiz page not served"

    # quizzes through the live services vs the faithful twin
    "$PY" tools/e2e_check.py 5 "$U" || fail "e2e mismatch"

    # compute comes back with an empty home (fresh machine / cleared disk), so it has forgotten
    # every session: the open quiz page must keep working without a reload
    kill $CPID; wait $CPID 2>/dev/null || true
    rm -rf "$TMP/server_home"
    start_compute "$B1"
    "$PY" tools/e2e_check.py 1 "$U" || fail "quiz failed after compute restart"
    grep -q "re-sending public keys" "$TMP/client.log" || fail "client did not re-provision after restart"
    echo "compute restart: client re-sent public keys and the next quiz passed"

    # guards (well-formed requests, so they test the guard itself and not the content-type check):
    # compute refuses a secret key or public key upload; scoring an unknown session is refused
    OCT=(-H "Content-Type: application/octet-stream")
    for k in sk.bin pk.bin; do
      code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${OCT[@]}" --data-binary x "$C/v1/keys/0123456789abcdef/$k")
      [ "$code" = 400 ] || fail "compute accepted a $k upload ($code)"
    done
    code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${OCT[@]}" --data-binary x "$C/v1/score/0123456789abcdef")
    [ "$code" = 400 ] || fail "compute scored an unknown session ($code)"
    [ -z "$(find "$TMP/server_home" -name sk.bin -o -name pk.bin)" ] || fail "sk.bin or pk.bin found under the compute home"
    [ -z "$(find "$TMP/client_home" -name sk.bin -perm +0077)" ] || fail "sk.bin is readable by group/others"
    [ "$(stat -f %Lp "$TMP/client_home")" = 700 ] || fail "client home is not 0700"
    echo "guards: sk.bin/pk.bin uploads refused, unknown session refused, compute holds neither; client home 0700, sk.bin 0600"

    # localhost hardening: browsers can't drive either service
    code=$(curl -s -o /dev/null -w "%{http_code}" -H "Origin: https://evil.example" "$C/v1/health")
    [ "$code" = 403 ] || fail "compute answered a browser Origin ($code)"
    code=$(curl -s -o /dev/null -w "%{http_code}" -X POST --data-binary x "$C/v1/score/0123456789abcdef")
    [ "$code" = 415 ] || fail "compute accepted a non-binary upload ($code)"
    code=$(curl -s -o /dev/null -w "%{http_code}" -H "Host: evil.example:$UP" "$U/api/status")
    [ "$code" = 403 ] || fail "client answered a foreign Host header ($code)"
    code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Origin: https://evil.example" -H "Content-Type: application/json" --data '{"answers":[]}' "$U/api/encrypt")
    [ "$code" = 403 ] || fail "client accepted a cross-origin POST ($code)"
    code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: text/plain" --data '{"answers":[]}' "$U/api/encrypt")
    [ "$code" = 415 ] || fail "client accepted a non-JSON POST ($code)"
    echo "hardening: browser Origin/foreign Host refused (403), wrong content types refused (415)"

    kill $CPID $UPID; wait 2>/dev/null || true; CPID=""; UPID=""
    echo "PASS ($B1)"
  done
done
