# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Compute backends for "Which Era Are You?": the ONLY place that knows where the encrypted math runs.

Every backend runs the same compiled `era_server` (same circuit, same keys, same ciphertext format).
They differ only in the command line that launches it. Everything above this module (the compute
service's HTTP API, the client service, the encryption/decryption flow, the web UI) is
backend-agnostic: the UI renders whatever `describe()` returns and never checks backend ids.

Backends:
  cpu       plain OpenFHE on this machine (no trace)
  sim       hollow FHETCH record -> local fhetch_sim replay       (a local rehearsal of the Fog run)
  sim-full  real-math record -> local replay + bit-for-bit ring-level check against OpenFHE
  fog       hollow record -> replay on the Niobium Fog via `fog submit`   (needs `fog login`)

To add or switch a backend, change this file only. See FOG.md for the Fog switch-over.
"""
import os
import re
import shutil

RING_CHECK_MARK = "ring-level identity check: replay == OpenFHE"


class BackendUnavailable(Exception):
    """The backend can't run on this machine yet. `fix` says what to do about it."""

    def __init__(self, problems):
        self.problems = problems          # list of (what is missing, how to fix it)
        super().__init__("; ".join(p for p, _ in problems))


class Backend:
    id = ""
    remote = False                        # True when ciphertext leaves this machine

    def __init__(self, build_dir, **_):
        self.server = os.path.join(build_dir, "era_server")

    def preflight(self):
        """Raise BackendUnavailable if this backend can't run. Must not contact any network service."""
        if not os.access(self.server, os.X_OK):
            raise BackendUnavailable([(f"{self.server} is not built", "run ./build.sh")])

    def command(self, job_dir):
        raise NotImplementedError

    def describe(self):
        """What the UI shows. `name` is bolded; `detail` follows it. Plain text, no HTML."""
        raise NotImplementedError

    def parse(self, stdout, stderr):
        """Backend-specific facts pulled from era_server's output, merged into the job metadata."""
        return {"ring_check": RING_CHECK_MARK in (stdout + stderr)}


class CpuBackend(Backend):
    id = "cpu"

    def command(self, job_dir):
        return [self.server, job_dir, "--cpu"]

    def describe(self):
        return {"id": self.id, "short": "local CPU", "name": "OpenFHE on this computer's CPU",
                "detail": "Fog hardware is not connected in this run.", "where": "the scoring service",
                "remote": self.remote}


class SimBackend(Backend):
    id = "sim"

    def command(self, job_dir):
        return [self.server, job_dir, "--hollow"]

    def describe(self):
        return {"id": self.id, "short": "Niobium simulator",
                "name": "Niobium's FHETCH simulator on this computer",
                "detail": "It replays the instruction trace this app records for a Fog run, as a local rehearsal "
                          "(not yet checked against the Fog itself). "
                          "Fog hardware is not connected in this run.",
                "where": "Niobium's simulator", "remote": self.remote}


class SimFullBackend(SimBackend):
    id = "sim-full"

    def command(self, job_dir):
        return [self.server, job_dir]      # real-math record: enables the ring-level identity check

    def describe(self):
        d = super().describe()
        d.update(id=self.id, short="Niobium simulator, full check",
                 detail="It records the circuit with real math, replays that instruction trace on the simulator, and "
                        "checks every result bit for bit against plain OpenFHE. Fog hardware is not connected in this run.")
        return d


class FogBackend(Backend):
    id = "fog"
    remote = True

    def __init__(self, build_dir, target=None, **_):
        super().__init__(build_dir)
        # FOG = the real Fog; FUNC_SIM = the Fog's hardware-free simulator target.
        self.target = target or os.environ.get("FOG_TARGET", "FOG")

    def preflight(self):
        problems = []
        try:
            super().preflight()
        except BackendUnavailable as e:
            problems += e.problems
        if not shutil.which("fog"):
            problems.append(("the `fog` CLI is not on PATH",
                             "in niobium-client: make install-cli, and put ~/.local/bin on PATH"))
        if not shutil.which("nbcc_fhetch_replay"):
            problems.append(("`nbcc_fhetch_replay` (the transport client fog hands off to) is not on PATH",
                             "in niobium-client: make install-cli"))
        fog_home = os.environ.get("FOG_HOME", os.path.expanduser("~/.fog"))
        if not os.path.exists(os.path.join(fog_home, "credentials")) and not os.environ.get("FOG_API_TOKEN"):
            problems.append(("no Fog API key (~/.fog/credentials or FOG_API_TOKEN)",
                             "run `fog login -u <your console email>`; "
                             "no account yet: https://console.niobium.co/request-account"))
        if problems:
            raise BackendUnavailable(problems)

    def command(self, job_dir):
        # The documented dispatch: fog provisions a job, sets NBCC_FHETCH_SERVER, and runs our server.
        # The ring-dim guard is never bypassed here: Niobium documents that the Fog runs exactly N = 2^16.
        return ["fog", "submit", self.server, job_dir, "--hollow", f"--target={self.target}"]

    def describe(self):
        return {"id": self.id, "short": "Niobium Fog", "name": "the Niobium Fog",
                "detail": f"Fog target {self.target}.", "where": "the Niobium Fog",
                "remote": self.remote, "target": self.target}

    def parse(self, stdout, stderr):
        meta = super().parse(stdout, stderr)
        m = re.search(r"\[fog\] assigned (\S+)", stderr)   # printed by `fog submit` once a worker is assigned
        meta["fog_job"] = m.group(1) if m else None
        return meta


BACKENDS = {b.id: b for b in (CpuBackend, SimBackend, SimFullBackend, FogBackend)}


def get(name, build_dir, **kw):
    if name not in BACKENDS:
        raise ValueError(f"unknown backend {name!r}; choose one of {', '.join(BACKENDS)}")
    return BACKENDS[name](build_dir, **kw)
