# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Compute backends for "Which Era Are You?": the ONLY place that knows where the encrypted math runs.

Every backend runs the same compiled `era_server` (same circuit, same keys, same ciphertext format).
They differ only in the command line that launches it. Everything above this module (the compute
service's HTTP API, the client service, the encryption/decryption flow, the web UI) is
backend-agnostic: the UI renders whatever `describe()` returns and never checks backend ids.

Backends:
  cpu       plain OpenFHE on this machine (no trace)
  sim       hollow FHETCH record -> local fhetch_sim replay       (a local rehearsal of the Fog run)
  sim-full  real-math record -> local replay + bit-for-bit ring-level check against OpenFHE
  fog       hollow record -> replay on the Niobium Fog via `fog submit`   (needs `fog login`)

To add or switch a backend, change this file only. See FOG.md for running on the Fog.
"""
import os
import re
import shutil

RING_CHECK_MARK = "ring-level identity check: replay == OpenFHE"


class BackendUnavailable(Exception):
    """The backend can't run on this machine yet. `fix` says what to do about it."""

    def __init__(self, problems):
        self.problems = problems          # list of (what is missing, how to fix it)
        super().__init__("; ".join(p for p, _ in problems))


class Backend:
    id = ""
    remote = False                        # True when ciphertext leaves this machine
    hollow = False                        # True when era_server must record WITHOUT real math (--hollow)

    def __init__(self, build_dir, **_):
        self.server = os.path.join(build_dir, "era_server")

    def preflight(self):
        """Raise BackendUnavailable if this backend can't run. Must not contact any network service."""
        if not os.access(self.server, os.X_OK):
            raise BackendUnavailable([(f"{self.server} is not built", "run ./build.sh")])

    def command(self, job_dir):
        raise NotImplementedError

    def describe(self):
        """What the UI shows. `name` is bolded; `detail` follows it. Plain text, no HTML."""
        raise NotImplementedError

    def parse(self, stdout, stderr, timeline=()):
        """Backend-specific facts pulled from era_server's output, merged into the job metadata.
        `timeline` is [(ms since launch, stderr line)] in arrival order (compute_service.run_timed).

        transport_ms is the time spent moving ciphertext to and from remote hardware. Local backends
        never move it, so it is None and the UI shows "n/a"."""
        return {"ring_check": RING_CHECK_MARK in (stdout + stderr), "transport_ms": None}


class CpuBackend(Backend):
    id = "cpu"

    def command(self, job_dir):
        return [self.server, job_dir, "--cpu"]

    def describe(self):
        return {"id": self.id, "short": "local CPU", "name": "OpenFHE on this computer's CPU",
                "detail": "Fog hardware is not connected in this run.", "where": "the scoring service",
                "remote": self.remote}


class SimBackend(Backend):
    id = "sim"
    hollow = True

    def command(self, job_dir):
        return [self.server, job_dir, "--hollow"]

    def describe(self):
        return {"id": self.id, "short": "Niobium simulator",
                "name": "Niobium's FHETCH simulator on this computer",
                "detail": "It replays the instruction trace this app records for a Fog run, as a local rehearsal. "
                          "Fog hardware is not connected in this run.",
                "where": "Niobium's simulator", "remote": self.remote}


class SimFullBackend(SimBackend):
    id = "sim-full"
    hollow = False                        # real math on purpose: it feeds the ring-level identity check

    def command(self, job_dir):
        return [self.server, job_dir]      # real-math record: enables the ring-level identity check

    def describe(self):
        d = super().describe()
        d.update(id=self.id, short="Niobium simulator, full check",
                 detail="It records the circuit with real math, replays that instruction trace on the simulator, and "
                        "checks every result bit for bit against plain OpenFHE. Fog hardware is not connected in this run.")
        return d


class FogBackend(Backend):
    id = "fog"
    remote = True
    hollow = True                         # the Fog gets a hollow trace; it never needs the real math

    # stderr lines that mark the phases of a `fog submit` run, in the order they appear:
    #   fog (niobium-client scripts/fog):      "[fog] assigned <job> -> <worker url>"
    #   nbcc_fhetch_replay (transport client): "[fog] upload <n>/<m> MB (<pct>%)" ... "[fog] upload complete …"
    #   era_server (app/server.cpp):           "[server] replay done in <ms> ms"
    ASSIGNED = re.compile(r"^\[fog\] assigned (\S+)")
    UPLOAD_START = re.compile(r"^\[fog\] upload \d+/\d+ MB")
    UPLOAD_DONE = re.compile(r"^\[fog\] upload complete")
    REPLAY_DONE = re.compile(r"^\[server\] replay done")
    UPLOAD_BYTES = re.compile(r"\[nbcc_fhetch_replay\] POSTing (\d+) bytes")   # stdout, exact size

    def __init__(self, build_dir, target=None, **_):
        super().__init__(build_dir)
        # FOG = the real Fog; FUNC_SIM = the Fog's hardware-free simulator target.
        self.target = target or os.environ.get("FOG_TARGET", "FOG")

    def preflight(self):
        problems = []
        try:
            super().preflight()
        except BackendUnavailable as e:
            problems += e.problems
        if not shutil.which("fog"):
            problems.append(("the `fog` CLI is not on PATH",
                             "in niobium-client: make install-cli, and put ~/.local/bin on PATH"))
        if not shutil.which("nbcc_fhetch_replay"):
            problems.append(("`nbcc_fhetch_replay` (the transport client fog hands off to) is not on PATH",
                             "in niobium-client: make install-cli"))
        fog_home = os.environ.get("FOG_HOME", os.path.expanduser("~/.fog"))
        if not os.path.exists(os.path.join(fog_home, "credentials")) and not os.environ.get("FOG_API_TOKEN"):
            problems.append(("no Fog API key (~/.fog/credentials or FOG_API_TOKEN)",
                             "run `fog login -u <your console email>`; "
                             "no account yet: https://console.niobium.co/request-account"))
        if problems:
            raise BackendUnavailable(problems)

    def command(self, job_dir):
        # The documented dispatch: fog provisions a job, sets NBCC_FHETCH_SERVER, and runs our server.
        # The ring-dim guard is never bypassed here: Niobium documents that the Fog runs exactly N = 2^16.
        return ["fog", "submit", self.server, job_dir, "--hollow", f"--target={self.target}"]

    def describe(self):
        return {"id": self.id, "short": "Niobium Fog", "name": "the Niobium Fog",
                "detail": f"Fog target {self.target}.", "where": "the Niobium Fog",
                "remote": self.remote, "target": self.target}

    def parse(self, stdout, stderr, timeline=()):
        meta = super().parse(stdout, stderr, timeline)
        m = self.ASSIGNED.search(stderr) or re.search(r"\[fog\] assigned (\S+)", stderr)
        meta["fog_job"] = m.group(1) if m else None
        meta.update(self.timing(stdout, timeline))
        return meta

    def timing(self, stdout, timeline):
        """Split a Fog run into phases from the timestamped stderr lines.

        upload_ms   first upload-progress line -> "upload complete": pure transport, measured.
        fog_wait_ms "upload complete" -> replay() returned: the Fog's own run plus the download of the
                    result. The transport client reports upload progress but not when the response
                    starts, so the download is counted here.
        fog_queue_ms launch -> worker assigned: `fog submit` provisioning / queue time.
        transport_ms the measured transport: upload_ms (plus download_ms when a client reports it).
        """
        def first(rx):
            return next((t for t, line in timeline if rx.search(line)), None)
        t_assigned, t_up0, t_up1, t_done = (first(rx) for rx in
                                            (self.ASSIGNED, self.UPLOAD_START, self.UPLOAD_DONE, self.REPLAY_DONE))
        upload = round(t_up1 - t_up0) if t_up0 is not None and t_up1 is not None else None
        m = self.UPLOAD_BYTES.search(stdout)
        return {"fog_queue_ms": round(t_assigned) if t_assigned is not None else None,
                "upload_ms": upload,
                "upload_bytes": int(m.group(1)) if m else None,
                "download_ms": None,
                "fog_wait_ms": round(t_done - t_up1) if t_up1 is not None and t_done is not None else None,
                "transport_ms": upload}


BACKENDS = {b.id: b for b in (CpuBackend, SimBackend, SimFullBackend, FogBackend)}


def get(name, build_dir, **kw):
    if name not in BACKENDS:
        raise ValueError(f"unknown backend {name!r}; choose one of {', '.join(BACKENDS)}")
    return BACKENDS[name](build_dir, **kw)
