# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Client service: the trusted local client of "Which Era Are You?", running on the quiz taker's computer.

This program (not the browser page) is the cryptographic client. It serves the web UI on localhost,
generates one CKKS key pair when it starts (shared by every quiz until it restarts), keeps the secret
key in its own owner-only home directory, and ships ONLY the crypto context and rotation keys to the
compute service. For each quiz it:
  1. turns the answers into an 8-number trait vector and encrypts it   (era_encrypt, public key)
  2. sends the ciphertext to the compute service, gets encrypted scores back
  3. decrypts the scores locally (era_decrypt, secret key) and picks the highest one

  python3 services/client_service.py [--port 8000] [--compute http://127.0.0.1:8001]
"""
import argparse
import hashlib
import http.server
import json
import mimetypes
import os
import secrets
import shutil
import subprocess
import threading
import time
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUIZ = json.load(open(os.path.join(ROOT, "data", "quiz.json")))
TRAITS = [t["id"] for t in QUIZ["traits"]]
BASELINE = QUIZ["baseline"]
JOBS = {}
JLOCK = threading.Lock()
KEEP_JOBS = 20            # recent quiz runs kept on disk (for the ciphertext download links)


def run(cmd, stdin=None):
    # Plaintext (the trait vector) goes over stdin, never argv: argv is visible to every process (ps).
    r = subprocess.run(cmd, input=stdin, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"{os.path.basename(cmd[0])} failed: {r.stderr.strip()[-400:]}")
    return json.loads(r.stdout.strip().splitlines()[-1])


def trait_vector(answers):
    """Same math as tools/twin.py: sum the option deltas, subtract the baseline, unit-normalize."""
    qs = QUIZ["questions"]
    if not isinstance(answers, list) or len(answers) != len(qs):
        raise ValueError("need one answer per question")
    raw = [0.0] * len(TRAITS)
    for q, a in zip(qs, answers):
        if not isinstance(a, int) or not 0 <= a < len(q["options"]):
            raise ValueError("answer out of range")
        for k, v in q["options"][a]["d"].items():
            raw[TRAITS.index(k)] += v
    c = [r - b for r, b in zip(raw, BASELINE)]
    n = sum(x * x for x in c) ** 0.5
    if n < 1e-9:
        raise ValueError("all-zero trait vector")
    return [x / n for x in c]


def preview(blob):
    """A real slice of the serialized ciphertext: hex from the middle of the coefficient data."""
    off = max(0, len(blob) // 2 - 384)
    return {"bytes": len(blob), "sha256": hashlib.sha256(blob).hexdigest(),
            "hex": blob[off: off + 768].hex(), "offset": off}


def post(url, data, timeout=900):
    req = urllib.request.Request(url, data=data, method="POST",
                                 headers={"Content-Type": "application/octet-stream"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read(), r.headers


def setup_keys():
    home = CFG.home
    shutil.rmtree(home, ignore_errors=True)
    os.makedirs(home, mode=0o700)          # era_keygen also forces 0700 on the home and 0600 on sk.bin
    info = run([os.path.join(CFG.build, "era_keygen"), home, str(CFG.ring_dim)])
    CFG.session = secrets.token_hex(16)
    CFG.keyinfo = info
    CFG.keyinfo["sizes"] = provision_keys()
    CFG.keyinfo["sk_bytes"] = os.path.getsize(os.path.join(home, "sk.bin"))
    print(f"[client] keys generated (ring dim {info['ring_dim']}); secret key stays in {home}; "
          f"sent cc/rk ({sum(CFG.keyinfo['sizes'].values()):,} bytes) to {CFG.compute}", flush=True)


def provision_keys():
    """Send what the server actually loads (crypto context + rotation keys) under this session.
    Never sk.bin; pk.bin isn't sent either, because era_server never reads it (nor does the Fog path)."""
    sizes = {}
    for name in ("cc.bin", "rk.bin"):
        blob = open(os.path.join(CFG.home, name), "rb").read()
        post(f"{CFG.compute}/v1/keys/{CFG.session}/{name}", blob)
        sizes[name] = len(blob)
    return sizes


def score_remote(blob):
    """POST the query ciphertext. If the compute service restarted and forgot our session, re-send the
    public keys once and retry, so a compute restart never breaks an open quiz page."""
    url = f"{CFG.compute}/v1/score/{CFG.session}"
    try:
        return post(url, blob)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        if e.code != 400 or "unknown session" not in detail:
            raise RuntimeError(f"scoring service error {e.code}: {_err_text(detail)}") from None
    print("[client] compute service forgot this session (restarted?); re-sending public keys", flush=True)
    provision_keys()
    try:
        return post(url, blob)
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"scoring service error {e.code}: {_err_text(e.read().decode(errors='replace'))}") from None


def _err_text(body):
    try:
        return json.loads(body).get("error", body)[:300]
    except ValueError:
        return body[:300]


def find_job(body):
    job = JOBS.get(body.get("job"))
    if not job:
        raise ValueError("this quiz run has expired (the helper restarted). Please take the quiz again.")
    return job


def prune_jobs():
    with JLOCK:
        for jid in list(JOBS)[:-KEEP_JOBS]:
            shutil.rmtree(os.path.dirname(JOBS.pop(jid)["query"]), ignore_errors=True)


class Handler(http.server.BaseHTTPRequestHandler):
    server_version = "EraClient/1"

    def log_message(self, *a):
        pass

    def _trusted(self, post):
        """Localhost hardening. The Host header must name this service (blocks DNS-rebinding pages),
        a browser-sent Origin must be this page's own origin, and POSTs must be JSON: a cross-site
        page can't send application/json without a CORS preflight, which we never approve."""
        host = (self.headers.get("Host") or "").lower()
        origin = self.headers.get("Origin")
        if host not in CFG.allowed_hosts:
            self._json(403, {"error": "unexpected Host header"}); return False
        if origin is not None and origin.lower() not in {f"http://{h}" for h in CFG.allowed_hosts}:
            self._json(403, {"error": "cross-origin request refused"}); return False
        if post and (self.headers.get("Content-Type") or "").split(";")[0].strip().lower() != "application/json":
            self._json(415, {"error": "expected Content-Type: application/json"}); return False
        return True

    def _send(self, code, body, ctype="application/json", extra=None):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def _json(self, code, obj):
        self._send(code, json.dumps(obj).encode())

    def do_GET(self):
        if not self._trusted(post=False):
            return
        p = self.path.split("?")[0]
        if p == "/api/quiz":
            # Answer text only: the trait weights ("d") stay here, so the page can't tell which traits
            # (or eras) an answer pushes toward. The trait vector is computed in trait_vector() below.
            q = {"traits": QUIZ["traits"],
                 "questions": [{"q": x["q"], "options": [{"t": o["t"]} for o in x["options"]]} for x in QUIZ["questions"]]}
            q["eras"] = [{k: e[k] for k in ("id", "name", "blurb", "colors")} for e in QUIZ["eras"]]
            return self._json(200, q)
        if p == "/api/status":
            try:
                with urllib.request.urlopen(f"{CFG.compute}/v1/health", timeout=5) as r:
                    health = json.loads(r.read())
            except Exception as e:  # noqa: BLE001
                health = {"ok": False, "error": str(e)}
            return self._json(200, {"keys": CFG.keyinfo, "compute_url": CFG.compute, "compute": health})
        if p == "/api/server-log":
            try:
                with urllib.request.urlopen(f"{CFG.compute}/v1/log", timeout=5) as r:
                    return self._send(200, r.read())
            except Exception:  # noqa: BLE001
                return self._json(200, {"lines": []})
        if p.startswith("/api/ciphertext/"):
            jid, kind = p.split("/")[3:5]
            job = JOBS.get(jid)
            if not job or kind not in ("query", "result"):
                return self._json(404, {"error": "unknown"})
            blob = open(job[kind], "rb").read()
            return self._send(200, blob, "application/octet-stream",
                              {"Content-Disposition": f'attachment; filename="era_{kind}_ciphertext.bin"'})
        # static files
        rel = "index.html" if p in ("/", "") else p.lstrip("/")
        web = os.path.join(ROOT, "web")
        path = os.path.normpath(os.path.join(web, rel))
        if not path.startswith(web + os.sep) or not os.path.isfile(path):
            return self._json(404, {"error": "not found"})
        ctype = mimetypes.guess_type(path)[0] or "application/octet-stream"
        self._send(200, open(path, "rb").read(), ctype)

    def do_POST(self):
        if not self._trusted(post=True):
            return
        try:
            n = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(n) or b"{}") if n < 100000 else {}
            if self.path == "/api/encrypt":
                return self._encrypt(body)
            if self.path == "/api/compute":
                return self._compute(body)
            if self.path == "/api/decrypt":
                return self._decrypt(body)
            self._json(404, {"error": "not found"})
        except (ValueError, KeyError) as e:
            self._json(400, {"error": str(e)})
        except Exception as e:  # noqa: BLE001
            self._json(500, {"error": str(e)})

    # 1. encrypt on this computer (the trusted local client)
    def _encrypt(self, body):
        u = trait_vector(body.get("answers"))
        jid = secrets.token_hex(8)
        jdir = os.path.join(CFG.home, "jobs", jid)
        os.makedirs(jdir, mode=0o700)
        q = os.path.join(jdir, "ct_query.bin")
        t0 = time.time()
        run([os.path.join(CFG.build, "era_encrypt"), CFG.home, q], stdin=",".join(repr(x) for x in u) + "\n")
        ms = (time.time() - t0) * 1000
        with JLOCK:
            JOBS[jid] = {"query": q, "result": os.path.join(jdir, "ct_result.bin")}
        prune_jobs()
        self._json(200, {"job": jid, "traits": dict(zip(TRAITS, u)), "encrypt_ms": round(ms),
                         "slots_used": 96, "slots_total": CFG.keyinfo["slots"],
                         "ciphertext": preview(open(q, "rb").read())})

    # 2. ship ciphertext to the compute service
    def _compute(self, body):
        job = find_job(body)
        blob = open(job["query"], "rb").read()
        t0 = time.time()
        try:
            out, headers = score_remote(blob)
        except OSError as e:          # connection refused / reset: compute is down
            print(f"[client] can't reach compute at {CFG.compute}: {getattr(e, 'reason', e)}", flush=True)
            raise RuntimeError("the scoring service isn't answering. Check that it's running, then try again. "
                               "Nothing unencrypted was sent.") from None
        rtt = (time.time() - t0) * 1000
        with open(job["result"], "wb") as f:
            f.write(out)
        meta = json.loads(headers.get("X-Era-Meta", "{}"))
        meta["round_trip_ms"] = round(rtt)
        self._json(200, {"meta": meta, "ciphertext": preview(out)})

    # 3. decrypt on this computer, pick the top score (the scoring side never sees this)
    def _decrypt(self, body):
        job = find_job(body)
        t0 = time.time()
        res = run([os.path.join(CFG.build, "era_decrypt"), CFG.home, job["result"]])
        ms = (time.time() - t0) * 1000
        scores = res["scores"]
        best = max(range(len(scores)), key=lambda i: scores[i])   # client-side argmax
        ranked = sorted(range(len(scores)), key=lambda i: -scores[i])
        self._json(200, {"scores": scores, "best": best, "ranked": ranked, "decrypt_ms": round(ms),
                         "precision_bits": res.get("precision_bits")})


def main():
    global CFG
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--bind", default="127.0.0.1")
    ap.add_argument("--compute", default="http://127.0.0.1:8001")
    ap.add_argument("--home", default=os.path.join(ROOT, "run_demo", "client_home"))
    ap.add_argument("--build", default=os.path.join(ROOT, "build"))
    ap.add_argument("--ring-dim", type=int, default=65536)
    ap.add_argument("--allow-host", action="append", default=[],
                    help="extra host[:port] the page may be served as (default: localhost / 127.0.0.1 / [::1])")
    CFG = ap.parse_args()
    CFG.compute = CFG.compute.rstrip("/")
    CFG.allowed_hosts = {f"{h}:{CFG.port}" for h in ("localhost", "127.0.0.1", "[::1]")} | {h.lower() for h in CFG.allow_host}
    os.umask(0o077)                        # everything this process writes (keys, job ciphertexts) is owner-only
    for i in range(30):
        try:
            setup_keys()
            break
        except OSError as e:
            if i == 29:
                raise
            print(f"[client] waiting for compute service at {CFG.compute} ({e})", flush=True)
            time.sleep(1)
    print(f"[client] open http://localhost:{CFG.port}", flush=True)
    http.server.ThreadingHTTPServer((CFG.bind, CFG.port), Handler).serve_forever()


if __name__ == "__main__":
    main()
