# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Compute service: the untrusted side of "Which Era Are You?".

Holds only: the CKKS crypto context and rotation keys (per client session), and the plaintext
era profiles. Never holds a secret key and refuses to run if one shows up. Receives an encrypted
trait vector, runs era_server on it, returns the encrypted scores, and deletes the job files.
Its log holds only sizes, timestamps and durations, and the first 8 characters of each session ID.

  python3 services/compute_service.py --backend cpu|sim|sim-full|fog [--port 8001] [--home DIR]
  python3 services/compute_service.py --backend fog --preflight   # readiness check, contacts nothing

The backend (where the encrypted math runs) lives in services/backends.py and is chosen here only,
by --backend or the ERA_BACKEND env var. The HTTP API below is identical for every backend.
"""
import argparse
import collections
import http.server
import json
import os
import re
import shutil
import subprocess
import threading
import time

import backends

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SESSION_RE = re.compile(r"^[a-f0-9]{16,64}$")
ALLOWED_KEYS = {"cc.bin", "rk.bin"}                # the only files a client may provision (era_server reads just these)
MAX_UPLOAD = 64 * 1024 * 1024

LOG = collections.deque(maxlen=200)
SEQ = [0]
LOCK = threading.Lock()                              # one FHE job at a time keeps memory predictable


def log(msg):
    line = f"{time.strftime('%H:%M:%S')}  {msg}"
    SEQ[0] += 1
    LOG.append(line)
    print("[compute]", line, flush=True)


def assert_no_secret_key(home):
    for dirpath, _, files in os.walk(home):
        if "sk.bin" in files:
            raise SystemExit(f"[compute] FATAL: secret key found in {dirpath}. Refusing to run.")


class Handler(http.server.BaseHTTPRequestHandler):
    server_version = "EraCompute/1"

    def log_message(self, *a):
        pass

    def _send(self, code, body=b"", ctype="application/json", headers=None):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        for k, v in (headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def _json(self, code, obj):
        self._send(code, json.dumps(obj).encode())

    def _body(self):
        n = int(self.headers.get("Content-Length", 0))
        if n <= 0 or n > MAX_UPLOAD:
            raise ValueError("bad body size")
        return self.rfile.read(n)

    def _from_browser(self):
        """Only the trusted client talks to this service, server to server. Browsers always attach an
        Origin header to cross-origin and POST requests; refuse those outright."""
        if self.headers.get("Origin") is not None:
            self._json(403, {"error": "browser requests are not accepted"}); return True
        return False

    def do_GET(self):
        if self._from_browser():
            return
        if self.path == "/v1/health":
            return self._json(200, {"ok": True, "backend": BACKEND.describe()})
        if self.path == "/v1/log":
            lines = list(LOG)[-40:]
            return self._json(200, {"lines": lines, "total": SEQ[0], "first": SEQ[0] - len(lines) + 1})
        self._json(404, {"error": "not found"})

    def do_POST(self):
        parts = self.path.strip("/").split("/")
        # Read the whole upload BEFORE answering, even when we are about to refuse it: replying early
        # and closing leaves the client mid-upload with a broken pipe instead of our 400.
        try:
            body = self._body()
        except ValueError as e:
            self.close_connection = True
            return self._json(413, {"error": str(e)})
        # checked only after the body is drained (see above)
        if self._from_browser():
            return
        if (self.headers.get("Content-Type") or "").split(";")[0].strip().lower() != "application/octet-stream":
            return self._json(415, {"error": "expected Content-Type: application/octet-stream"})
        try:
            # POST /v1/keys/<session>/<cc.bin|rk.bin>
            if len(parts) == 4 and parts[:2] == ["v1", "keys"]:
                sid, name = parts[2], parts[3]
                if not SESSION_RE.match(sid) or name not in ALLOWED_KEYS:
                    return self._json(400, {"error": "only cc.bin and rk.bin may be provisioned"})
                data = body
                sdir = os.path.join(CFG.home, "sessions", sid)
                os.makedirs(sdir, exist_ok=True)
                with open(os.path.join(sdir, name), "wb") as f:
                    f.write(data)
                log(f"setup: received {name} ({len(data):,} bytes) for session {sid[:8]}")
                return self._json(200, {"ok": True})

            # POST /v1/score/<session>   body = serialized query ciphertext
            if len(parts) == 3 and parts[:2] == ["v1", "score"]:
                sid = parts[2]
                sdir = os.path.join(CFG.home, "sessions", sid)
                if not SESSION_RE.match(sid) or not all(
                        os.path.exists(os.path.join(sdir, k)) for k in ALLOWED_KEYS):
                    return self._json(400, {"error": "unknown session; provision keys first"})
                ct = body
                with LOCK:
                    return self._score(sid, sdir, ct)
        except ValueError as e:
            return self._json(400, {"error": str(e)})
        self._json(404, {"error": "not found"})

    def _score(self, sid, sdir, ct):
        job = os.path.join(sdir, f"job_{time.time_ns()}")
        os.makedirs(job)
        try:
            for k in ("cc.bin", "rk.bin"):
                os.link(os.path.join(sdir, k), os.path.join(job, k))
            shutil.copy(os.path.join(ROOT, "data", "eras.csv"), job)
            with open(os.path.join(job, "ct_query.bin"), "wb") as f:
                f.write(ct)
            assert_no_secret_key(job)
            log(f"received {len(ct):,} bytes of ciphertext from session {sid[:8]}. No key to open it.")

            desc = BACKEND.describe()
            log(f"computing 12 encrypted dot products on {desc['name']}")
            t0 = time.time()
            try:
                r = subprocess.run(BACKEND.command(job), cwd=job, capture_output=True, text=True,
                                   timeout=CFG.timeout)
            except subprocess.TimeoutExpired:
                log(f"server timed out after {CFG.timeout} s")
                return self._json(504, {"error": f"scoring took longer than {CFG.timeout} s"})
            ms = (time.time() - t0) * 1000
            if r.returncode != 0:
                log(f"server failed (exit {r.returncode})")
                print(r.stdout[-4000:], r.stderr[-4000:], flush=True)
                return self._json(502, {"error": f"era_server failed with exit {r.returncode}",
                                        "detail": r.stderr[-1500:]})
            summary = {}
            for line in r.stdout.splitlines():
                if line.startswith("{"):
                    summary = json.loads(line)
            with open(os.path.join(job, "ct_result.bin"), "rb") as f:
                out = f.read()
            log(f"returned {len(out):,} bytes, still encrypted ({ms:.0f} ms)")
            meta = {"backend": desc, "server_mode": summary.get("mode", BACKEND.id),
                    "server_ms": round(ms), "bytes_in": len(ct), "bytes_out": len(out),
                    "ring_dim": summary.get("ring_dim"),
                    "trace_instructions": _trace_count(r.stdout + r.stderr)}
            meta.update(BACKEND.parse(r.stdout, r.stderr))
            return self._send(200, out, "application/octet-stream", {"X-Era-Meta": json.dumps(meta)})
        finally:
            if not CFG.keep_jobs:
                shutil.rmtree(job, ignore_errors=True)


def _trace_count(stderr):
    m = re.search(r"Executing (\d+) instructions", stderr) or re.search(r"Instructions:\s+(\d+)", stderr)
    return int(m.group(1)) if m else None


def main():
    global CFG, BACKEND
    ap = argparse.ArgumentParser()
    ap.add_argument("--backend", "--mode", dest="backend", choices=list(backends.BACKENDS),
                    default=os.environ.get("ERA_BACKEND", "sim"))
    ap.add_argument("--port", type=int, default=8001)
    ap.add_argument("--bind", default="127.0.0.1")
    ap.add_argument("--home", default=os.path.join(ROOT, "run_demo", "server_home"))
    ap.add_argument("--build", default=os.path.join(ROOT, "build"))
    ap.add_argument("--fog-target", default=os.environ.get("FOG_TARGET", "FOG"))
    ap.add_argument("--preflight", action="store_true", help="check the backend can run, then exit")
    ap.add_argument("--timeout", type=int, default=900)
    ap.add_argument("--keep-jobs", action="store_true", help="keep job dirs for debugging")
    CFG = ap.parse_args()
    BACKEND = backends.get(CFG.backend, CFG.build, target=CFG.fog_target)
    try:
        BACKEND.preflight()
    except backends.BackendUnavailable as e:
        print(f"[compute] backend '{BACKEND.id}' is not ready:")
        for what, fix in e.problems:
            print(f"  - {what}\n      fix: {fix}")
        if BACKEND.id == "fog":
            print("  Everything else works without the Fog: ./start_local.sh sim")
        raise SystemExit(3)
    if CFG.preflight:
        print(f"[compute] backend '{BACKEND.id}' is ready ({BACKEND.describe()['name']}). Nothing was contacted.")
        return
    os.makedirs(CFG.home, exist_ok=True)
    assert_no_secret_key(CFG.home)
    log(f"compute service up on {CFG.bind}:{CFG.port}, backend={BACKEND.id}. Holding no secret keys.")
    http.server.ThreadingHTTPServer((CFG.bind, CFG.port), Handler).serve_forever()


if __name__ == "__main__":
    main()
