// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// Shared definitions for the "Which Era Are You?" FHE programs.
//
// Slot layout (one CKKS ciphertext, 96 used slots):
//   client packs   x[8*e + t] = u_t          (the user's unit trait vector, copied into 12 blocks)
//   server packs   w[8*e + t] = P_e,t        (era e's unit profile vector, plaintext)
//   circuit        y = x * w ; y += rot(y,1) ; y += rot(y,2) ; y += rot(y,4)
//   result         y[8*e] = sum_t u_t * P_e,t = cosine(user, era e)
#pragma once

#include "openfhe.h"

#include <cmath>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

namespace era {

using namespace lbcrypto;

constexpr int kTraits = 8;                       // block size; power of two for rotate-and-add
constexpr int kEras = 12;
constexpr int kSlotsUsed = kTraits * kEras;      // 96
inline const std::vector<int32_t> kRotations = {1, 2, 4};

// ---- files that live in each home ----
inline const char* kCC = "cc.bin";               // crypto context (client + server)
inline const char* kPK = "pk.bin";               // public key (client only: era_encrypt; not sent to the server)
inline const char* kSK = "sk.bin";               // SECRET key (client only, never on the server)
inline const char* kRK = "rk.bin";               // rotation keys (server needs them)
inline const char* kCtIn = "ct_query.bin";       // encrypted trait vector
inline const char* kCtOut = "ct_result.bin";     // encrypted scores
inline const char* kModel = "eras.csv";          // plaintext era profiles (server)

inline std::string join(const std::string& dir, const std::string& f) {
    return (std::filesystem::path(dir) / f).string();
}

template <typename T>
inline void load(const std::string& path, T& obj) {
    if (!Serial::DeserializeFromFile(path, obj, SerType::BINARY))
        throw std::runtime_error("failed to load " + path);
}

template <typename T>
inline void save(const std::string& path, const T& obj) {
    if (!Serial::SerializeToFile(path, obj, SerType::BINARY))
        throw std::runtime_error("failed to write " + path);
}

// Plaintext era profiles, one row per era, unit-normalized (written by tools/twin.py export).
struct Model {
    std::vector<std::string> ids;
    std::vector<std::vector<double>> profiles;
};

inline Model load_model(const std::string& path) {
    std::ifstream in(path);
    if (!in) throw std::runtime_error("cannot open model " + path);
    Model m;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::stringstream ss(line);
        std::string cell;
        std::getline(ss, cell, ',');
        m.ids.push_back(cell);
        std::vector<double> row;
        while (std::getline(ss, cell, ',')) row.push_back(std::stod(cell));
        if ((int)row.size() != kTraits) throw std::runtime_error("model row has wrong width");
        m.profiles.push_back(row);
    }
    if ((int)m.ids.size() != kEras) throw std::runtime_error("model must have 12 eras");
    return m;
}

inline std::vector<double> pack_model(const Model& m) {
    std::vector<double> w(kSlotsUsed, 0.0);
    for (int e = 0; e < kEras; ++e)
        for (int t = 0; t < kTraits; ++t) w[e * kTraits + t] = m.profiles[e][t];
    return w;
}

// THE circuit. Every run mode (CPU, simulator, Fog) calls this one function, so the math
// cannot drift between modes. One plaintext-ciphertext multiply (depth 1) + 3 rotations.
inline Ciphertext<DCRTPoly> run_circuit(CryptoContext<DCRTPoly>& cc,
                                        const Ciphertext<DCRTPoly>& query,
                                        const Plaintext& eraProfiles) {
    auto y = cc->EvalMult(query, eraProfiles);
    for (int32_t r : kRotations) y = cc->EvalAdd(y, cc->EvalRotate(y, r));
    // Drop to one RNS tower: decrypt only needs the last tower, and it shrinks what travels back.
    return cc->Compress(y, 1);
}

}  // namespace era
