// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// era_decrypt — CLIENT side. Decrypts the encrypted scores with the secret key and prints the
// 12 era scores (slot 8*e) plus the winning era index as JSON. The server never sees any of this.
//
// Usage: era_decrypt <client_home> <result_ciphertext>
#include "common.hpp"

#include <iomanip>

using namespace era;

int main(int argc, char* argv[]) {
    if (argc < 3) { std::cerr << "usage: era_decrypt <client_home> <result_ct>\n"; return 2; }
    const std::string home = argv[1];
    CryptoContext<DCRTPoly> cc;
    PrivateKey<DCRTPoly> sk;
    Ciphertext<DCRTPoly> ct;
    load(join(home, kCC), cc);
    load(join(home, kSK), sk);
    load(argv[2], ct);

    Plaintext pt;
    cc->Decrypt(sk, ct, &pt);
    pt->SetLength(kSlotsUsed);
    auto v = pt->GetRealPackedValue();

    int best = 0;
    std::cout << std::setprecision(12) << "{\"scores\":[";
    for (int e = 0; e < kEras; ++e) {
        double s = v[e * kTraits];
        if (s > v[best * kTraits]) best = e;
        std::cout << (e ? "," : "") << s;
    }
    std::cout << "],\"best\":" << best << ",\"precision_bits\":" << pt->GetLogPrecision() << "}" << std::endl;
    return 0;
}
