// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// era_encrypt — CLIENT side. Reads the user's 8-number trait vector, enforces the input bounds,
// copies it into 12 blocks of 8 slots, and encrypts it under the public key.
//
// Usage: echo "u0,u1,...,u7" | era_encrypt <client_home> <out_ciphertext>
// The plaintext vector arrives on stdin, never on the command line: argv is visible to every process
// on the machine (ps), stdin is a private pipe from the trusted client.
// Bounds (enforced here, before anything is encrypted): 8 finite values, each in [-1, 1],
// Euclidean norm within 1e-6 of 1 (the client unit-normalizes before calling us).
#include "common.hpp"

using namespace era;

int main(int argc, char* argv[]) {
    if (argc != 3) { std::cerr << "usage: echo u0,...,u7 | era_encrypt <client_home> <out>\n"; return 2; }
    const std::string home = argv[1];
    const std::string out = argv[2];

    std::string line;
    if (!std::getline(std::cin, line)) { std::cerr << "REJECT: no trait vector on stdin\n"; return 3; }
    std::vector<double> u;
    std::stringstream ss(line);
    std::string cell;
    while (std::getline(ss, cell, ',')) u.push_back(std::stod(cell));
    double n2 = 0;
    for (double x : u) {
        if (!std::isfinite(x) || x < -1.0 || x > 1.0) { std::cerr << "REJECT: value out of [-1,1]\n"; return 3; }
        n2 += x * x;
    }
    if ((int)u.size() != kTraits) { std::cerr << "REJECT: need exactly 8 values\n"; return 3; }
    if (std::fabs(std::sqrt(n2) - 1.0) > 1e-6) { std::cerr << "REJECT: vector is not unit length\n"; return 3; }

    CryptoContext<DCRTPoly> cc;
    PublicKey<DCRTPoly> pk;
    load(join(home, kCC), cc);
    load(join(home, kPK), pk);

    std::vector<double> x(kSlotsUsed);
    for (int e = 0; e < kEras; ++e)
        for (int t = 0; t < kTraits; ++t) x[e * kTraits + t] = u[t];

    auto ct = cc->Encrypt(pk, cc->MakeCKKSPackedPlaintext(x));
    save(out, ct);
    std::cout << "{\"ok\":true,\"bytes\":" << std::filesystem::file_size(out) << "}" << std::endl;
    return 0;
}
