// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// era_keygen — CLIENT side. Creates the CKKS context and all keys in the client home.
// The secret key is written ONLY here. The client later ships cc/pk/rk (never sk) to the server.
//
// Usage: era_keygen <client_home> [ring_dim]      (ring_dim default 65536 = 2^16, the size Niobium documents for the Fog)
#include "common.hpp"

#include <sys/stat.h>

using namespace era;

int main(int argc, char* argv[]) {
    if (argc < 2) { std::cerr << "usage: era_keygen <client_home> [ring_dim]\n"; return 2; }
    const std::string home = argv[1];
    const uint32_t ringDim = argc > 2 ? std::stoul(argv[2]) : (1u << 16);
    // Private key storage: everything this program creates is owner-only (files 0600, dirs 0700)
    // from the moment it exists, and the home itself is forced to 0700 even if the caller made it.
    umask(077);
    namespace fs = std::filesystem;
    fs::create_directories(home);
    fs::permissions(home, fs::perms::owner_all, fs::perm_options::replace);

    CCParams<CryptoContextCKKSRNS> p;
    p.SetMultiplicativeDepth(1);           // one plaintext x ciphertext multiply
    p.SetScalingModSize(50);               // ~50 bits of scale: far more precision than a quiz needs
    p.SetFirstModSize(60);
    p.SetScalingTechnique(FLEXIBLEAUTO);
    p.SetSecretKeyDist(UNIFORM_TERNARY);
    p.SetRingDim(ringDim);
    // At N = 2^16 with this small modulus the parameters are well above the 128-bit standard,
    // so we ask OpenFHE to enforce it. A deliberately tiny test ring skips the check.
    p.SetSecurityLevel(ringDim == (1u << 16) ? HEStd_128_classic : HEStd_NotSet);

    auto cc = GenCryptoContext(p);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);

    auto kp = cc->KeyGen();
    cc->EvalRotateKeyGen(kp.secretKey, kRotations);

    save(join(home, kCC), cc);
    save(join(home, kPK), kp.publicKey);
    save(join(home, kSK), kp.secretKey);
    std::ofstream rk(join(home, kRK), std::ios::binary);
    if (!cc->SerializeEvalAutomorphismKey(rk, SerType::BINARY)) throw std::runtime_error("rk");
    rk.close();
    fs::permissions(join(home, kSK), fs::perms::owner_read | fs::perms::owner_write, fs::perm_options::replace);

    std::cout << "{\"ring_dim\":" << cc->GetRingDimension()
              << ",\"slots\":" << cc->GetRingDimension() / 2
              << ",\"towers\":" << cc->GetElementParams()->GetParams().size() << "}" << std::endl;
    return 0;
}
