// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// era_server — COMPUTE side. Never holds the secret key.
//
// Reads from its home: cc.bin, rk.bin (rotation keys), eras.csv (plaintext era profiles),
// ct_query.bin (the user's encrypted trait vector). Computes the 12 encrypted era scores with
// run_circuit() and writes ct_result.bin, still encrypted.
//
// Run modes (same circuit in every mode):
//   --cpu                 plain OpenFHE on this CPU, no trace
//   (default)             record a FHETCH trace with niobium::compiler() and replay() it:
//                           * locally through fhetch_sim when NBCC_FHETCH_SERVER is unset  (--sim)
//                           * on the Niobium Fog when launched under `fog submit`           (Fog)
//   --hollow              (consumed by niobium::compiler().init) record without real math
//   --no-ring-dim-check   local testing of a ring smaller than 2^16 only; never used for the Fog
//
// Usage: era_server <server_home> [--cpu] [--hollow] [--no-ring-dim-check] [--target T]
#include "common.hpp"
#include "niobium/compiler.h"

#include <chrono>

using namespace era;

static int ring_level_diff(const Ciphertext<DCRTPoly>& a, const Ciphertext<DCRTPoly>& b) {
    const auto& ae = a->GetElements();
    const auto& be = b->GetElements();
    if (ae.size() != be.size()) return -1;
    int diverged = 0;
    for (size_t c = 0; c < ae.size(); ++c) {
        const auto& at = ae[c].GetAllElements();
        const auto& bt = be[c].GetAllElements();
        if (at.size() != bt.size()) return -1;
        for (size_t t = 0; t < at.size(); ++t) {
            const auto& av = at[t].GetValues();
            const auto& bv = bt[t].GetValues();
            size_t diffs = 0;
            for (size_t i = 0; i < av.GetLength(); ++i) diffs += (av[i] != bv[i]);
            std::cerr << "[server] ring-level check comp=" << c << " tower=" << t
                      << (diffs ? " DIVERGE (" + std::to_string(diffs) + " coeffs)" : " MATCH") << "\n";
            diverged += diffs ? 1 : 0;
        }
    }
    return diverged;
}

int main(int argc, char* argv[]) {
    // Consumes the Niobium flags (--hollow, --target, --no-ring-dim-check, ...) from argv.
    niobium::compiler().init(argc, argv);

    std::string home;
    bool cpu = false;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--cpu") cpu = true;
        else if (a.rfind("--", 0) != 0 && home.empty()) home = a;
    }
    if (home.empty()) { std::cerr << "usage: era_server <server_home> [--cpu]\n"; return 2; }

    // Trust-boundary guard: refuse to run if a secret key is anywhere in the server home.
    for (const auto& f : std::filesystem::directory_iterator(home)) {
        if (f.path().filename() == kSK) {
            std::cerr << "[server] FATAL: found a secret key in the server home. Refusing to start.\n";
            return 4;
        }
    }

    auto t0 = std::chrono::steady_clock::now();
    CryptoContext<DCRTPoly> cc;
    load(join(home, kCC), cc);
    {
        std::ifstream rk(join(home, kRK), std::ios::binary);
        if (!rk || !cc->DeserializeEvalAutomorphismKey(rk, SerType::BINARY))
            throw std::runtime_error("failed to load rotation keys");
    }
    Ciphertext<DCRTPoly> query;
    load(join(home, kCtIn), query);
    Model model = load_model(join(home, kModel));
    // Encode the plaintext era profiles BEFORE any recording starts so the recorder can tag them.
    Plaintext eras = cc->MakeCKKSPackedPlaintext(pack_model(model));

    std::cerr << "[server] received " << std::filesystem::file_size(join(home, kCtIn))
              << " bytes of ciphertext (no key to open it)\n";

    Ciphertext<DCRTPoly> result;
    std::string mode;
    double replayMs = -1;            // time inside replay(): for the Fog, upload + remote run + download
    if (cpu) {
        mode = "cpu";
        result = run_circuit(cc, query, eras);
    } else {
        const char* fogServer = std::getenv("NBCC_FHETCH_SERVER");
        mode = (fogServer && *fogServer) ? "fog" : "sim";
        niobium::compiler().set_program_info("era_server", "1.0",
                                             "Which Era Are You? encrypted era scoring");
        niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);
        niobium::Compiler::CacheParameters params;
        params.push_back({"workload", "era_quiz_dot12x8"});
        niobium::compiler().cache_parameters(params);

        niobium::compiler().capture_crypto_context(cc);
        niobium::compiler().tag_input("query", query);
        niobium::compiler().tag_input("era_profiles", eras);
        niobium::compiler().tag_keys(cc);

        const bool hollow = niobium::compiler().is_hollow_mode();
        Ciphertext<DCRTPoly> recorded;
        if (!niobium::compiler().is_cache_valid()) {
            niobium::compiler().enable_hollow_mode(hollow);
            niobium::compiler().start();
            auto out = run_circuit(cc, query, eras);
            niobium::compiler().probe("scores", out);
            niobium::compiler().stop();
            niobium::compiler().enable_hollow_mode(false);
            if (!hollow) recorded = out;
        }
        auto r0 = std::chrono::steady_clock::now();
        if (!niobium::compiler().replay()) { std::cerr << "[server] replay failed\n"; return 1; }
        replayMs = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - r0).count();
        // Printed as soon as replay() returns: the compute service timestamps this line to split the
        // Fog's upload from its run + download (services/backends.py, FogBackend.parse).
        std::cerr << "[server] replay done in " << replayMs << " ms\n";
        if (!niobium::compiler().result(cc, "scores", result)) {
            std::cerr << "[server] could not read replayed result\n";
            return 1;
        }
        if (recorded) {
            int d = ring_level_diff(recorded, result);
            if (d != 0) { std::cerr << "[server] ring-level identity check FAILED\n"; return 5; }
            std::cerr << "[server] ring-level identity check: replay == OpenFHE, bit for bit\n";
        }
        mode += hollow ? "-hollow" : "-real";
    }

    // run_circuit() ends with Compress(y, 1), so the result that travels back (from the Fog and then to
    // the client) carries a single RNS tower. Report the tower count so the UI and tests can see it.
    const auto towersOut = result->GetElements().at(0).GetNumOfElements();
    save(join(home, kCtOut), result);
    double ms = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
    auto outBytes = std::filesystem::file_size(join(home, kCtOut));
    std::cerr << "[server] returned " << outBytes << " bytes, still encrypted (compressed to "
              << towersOut << " RNS tower" << (towersOut == 1 ? "" : "s") << ")\n";
    std::cout << "{\"mode\":\"" << mode << "\",\"ms\":" << ms << ",\"bytes_out\":" << outBytes
              << ",\"ring_dim\":" << cc->GetRingDimension() << ",\"towers_out\":" << towersOut
              << ",\"replay_ms\":";
    if (replayMs < 0) std::cout << "null"; else std::cout << replayMs;
    std::cout << "}" << std::endl;
    return 0;
}
