# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Compare decrypted FHE scores against the faithful twin. Exit 1 on FAIL.

Usage: compare.py <decrypted.jsonl> <n_records>
Each line of decrypted.jsonl is era_decrypt's JSON for twin case i (data/twin_cases.json).
"""
import json
import os
import sys

TOL = 1e-6   # encryption-noise tolerance on a cosine score in [-1, 1]; observed error is ~1e-10
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cases = json.load(open(os.path.join(ROOT, "data", "twin_cases.json")))
quiz = json.load(open(os.path.join(ROOT, "data", "quiz.json")))
ids = [e["id"] for e in quiz["eras"]]
rows = [json.loads(l) for l in open(sys.argv[1]) if l.strip()]
n = int(sys.argv[2])
assert len(rows) == n, f"expected {n} results, got {len(rows)}"

errs, flips = [], 0
for i, r in enumerate(rows):
    twin = cases[i]
    e = max(abs(a - b) for a, b in zip(r["scores"], twin["scores"]))
    errs.append(e)
    fhe_era = ids[r["best"]]
    flips += fhe_era != twin["era"]
    if i == 0:
        print(f"  your era (record 0): {quiz['eras'][r['best']]['name']}   (twin says: {twin['era']})")
print(f"  encryption fidelity over {n} record(s): max |FHE - twin| = {max(errs):.3e}, "
      f"mean = {sum(errs)/n:.3e}, tolerance {TOL:g}, era flips = {flips}")
ok = max(errs) <= TOL and flips == 0
print("  PASS: encryption did not change any score beyond noise or any era result" if ok else "  FAIL")
sys.exit(0 if ok else 1)
