# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""End-to-end check through the running services: random answer sheets -> encrypt -> compute -> decrypt,
compared against the plaintext twin. Usage: python3 tools/e2e_check.py [n] [client_url]"""
import json, os, random, sys, urllib.request
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import twin
N = int(sys.argv[1]) if len(sys.argv) > 1 else 10
URL = sys.argv[2] if len(sys.argv) > 2 else "http://localhost:8000"
def post(p, b):
    r = urllib.request.urlopen(urllib.request.Request(URL + p, json.dumps(b).encode(), {"Content-Type": "application/json"}))
    return json.loads(r.read())
rng = random.Random(42); worst = 0; flips = 0; mode = None
for i in range(N):
    a = [rng.randrange(len(q)) for q in twin.OPT]
    e = post("/api/encrypt", {"answers": a}); c = post("/api/compute", {"job": e["job"]}); d = post("/api/decrypt", {"job": e["job"]})
    ref = twin.scores(a); mode = c["meta"]["server_mode"]
    worst = max(worst, max(abs(x - y) for x, y in zip(d["scores"], ref)))
    flips += d["best"] != int(ref.argmax())
print(f"{N} quizzes via services (server mode {mode}): max |FHE - twin| = {worst:.2e}, era flips = {flips}")
sys.exit(0 if worst < 1e-6 and flips == 0 else 1)
