# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Faithful plaintext twin of the encrypted era scoring.

The twin mirrors the FHE circuit slot for slot:
  client:  answers -> trait vector u (8 traits) -> unit-normalize -> replicate into 12 blocks of 8 slots
  server:  slotwise multiply by the packed era-profile plaintext (each profile unit-normalized)
           then rotate-and-add by 1, 2, 4 so slot 8*e holds the dot product for era e
  client:  read slots 0, 8, 16, ... -> 12 cosine scores -> argmax -> era

Usage:
  python3 tools/twin.py sweep            # exhaustive sweep over every answer combination
  python3 tools/twin.py score 0 1 2 ...  # score one answer sheet (option index per question)
  python3 tools/twin.py export           # write data/eras.csv (server model) + data/twin_cases.json
"""
import itertools
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUIZ = json.load(open(os.path.join(ROOT, "data", "quiz.json")))
TRAITS = [t["id"] for t in QUIZ["traits"]]
T = len(TRAITS)                 # 8 traits -> block size 8 (power of two for rotate-and-add)
E = len(QUIZ["eras"])           # 12 eras
BLOCK = 8
assert T == BLOCK


def option_vec(opt):
    v = np.zeros(T)
    for k, x in opt["d"].items():
        v[TRAITS.index(k)] = x
    return v


OPT = [[option_vec(o) for o in q["options"]] for q in QUIZ["questions"]]


def era_matrix():
    M = np.array([[e["profile"][t] for t in TRAITS] for e in QUIZ["eras"]], dtype=float)
    return M / np.linalg.norm(M, axis=1, keepdims=True)


# Baseline = the expected raw trait sum if every question were answered uniformly at random.
# Subtracting it means u measures how *you* differ from a typical answer sheet, which keeps
# every era reachable (without it the most common traits pull everyone toward one era).
BASELINE = sum(np.mean(q, axis=0) for q in OPT)


def trait_vector(answers):
    u = sum(OPT[i][a] for i, a in enumerate(answers)) - BASELINE
    n = np.linalg.norm(u)
    if n < 1e-9:
        raise ValueError("all-zero trait vector")
    return u / n


def packed_client_slots(u):
    return np.tile(u, E)                       # length 96


def packed_server_plaintext():
    return era_matrix().reshape(-1)            # length 96, block e = profile of era e


def slot_circuit(x, w, nslots=128):
    """Exact slot-level model of the server circuit, including cyclic rotation over nslots."""
    a = np.zeros(nslots); a[: len(x)] = x
    b = np.zeros(nslots); b[: len(w)] = w
    y = a * b
    for r in (1, 2, 4):
        y = y + np.roll(y, -r)                  # EvalRotate(y, r): slot i <- slot i+r
    return y


def scores(answers):
    u = trait_vector(answers)
    y = slot_circuit(packed_client_slots(u), packed_server_plaintext())
    s = y[0 : E * BLOCK : BLOCK]
    ref = era_matrix() @ u                      # the reference: plain cosine similarity
    assert np.allclose(s, ref, atol=1e-12)
    return s


def sweep():
    # Vectorized: every answer sheet = (sum over the first half) + (sum over the second half), so the
    # full sweep is a chunked outer sum instead of a Python loop over 4^12 = 16.7M sheets.
    M = era_matrix()
    def all_sums(qs):
        acc = np.zeros((1, T))
        for q in qs:
            acc = (acc[:, None, :] + np.array(q)[None, :, :]).reshape(-1, T)
        return acc
    h = len(OPT) // 2
    A, B = all_sums(OPT[:h]), all_sums(OPT[h:])
    counts = np.zeros(E, int)
    margins = []
    for i in range(0, len(A), 64):
        U = (A[i:i + 64, None, :] + B[None, :, :]).reshape(-1, T) - BASELINE
        U /= np.linalg.norm(U, axis=1, keepdims=True)
        S = U @ M.T
        counts += np.bincount(S.argmax(1), minlength=E)
        o = np.sort(S, axis=1)
        margins.append(o[:, -1] - o[:, -2])
    margins = np.concatenate(margins)
    print(f"{len(margins)} answer combinations")
    for e, n in zip(QUIZ["eras"], counts):
        print(f"  {e['name']:32s} {n:7d}  {100*n/len(margins):5.1f}%")
    print(f"top-1 vs top-2 margin: min {margins.min():.4f}  median {np.median(margins):.4f}  "
          f"<0.001: {np.mean(margins<1e-3)*100:.3f}%  <0.01: {np.mean(margins<1e-2)*100:.2f}%")
    print("era-era cosine (max off-diagonal):")
    C = M @ M.T; np.fill_diagonal(C, -1)
    i, j = np.unravel_index(np.argmax(C), C.shape)
    print(f"  {QUIZ['eras'][i]['name']} ~ {QUIZ['eras'][j]['name']}: {C[i,j]:.3f}")
    return counts, margins


def export():
    M = era_matrix()
    with open(os.path.join(ROOT, "data", "eras.csv"), "w") as f:
        f.write("# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).\n")
        f.write("# era_id," + ",".join(TRAITS) + "  (unit-normalized; the server's plaintext model)\n")
        for e, row in zip(QUIZ["eras"], M):
            f.write(e["id"] + "," + ",".join(f"{x:.17g}" for x in row) + "\n")
    rng = np.random.default_rng(7)
    cases = []
    for _ in range(25):
        a = [int(rng.integers(len(q))) for q in OPT]
        u = trait_vector(a)
        s = scores(a)
        cases.append({"answers": a, "u": u.tolist(), "scores": s.tolist(),
                      "era": QUIZ["eras"][int(np.argmax(s))]["id"]})
    json.dump(cases, open(os.path.join(ROOT, "data", "twin_cases.json"), "w"), indent=1)
    QUIZ["baseline"] = [round(float(x), 12) for x in BASELINE]
    json.dump(QUIZ, open(os.path.join(ROOT, "data", "quiz.json"), "w"), indent=2, ensure_ascii=False)
    print("wrote data/eras.csv and data/twin_cases.json")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "sweep"
    if cmd == "sweep":
        sweep()
    elif cmd == "score":
        a = [int(x) for x in sys.argv[2:]]
        s = scores(a)
        for e, x in sorted(zip(QUIZ["eras"], s), key=lambda p: -p[1]):
            print(f"{x:+.4f}  {e['name']}")
    elif cmd == "export":
        export()
