// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// UI for "Which Era Are You?". Every number in the proof comes from the real run: the ciphertext
// bytes, their sizes and hashes, the scoring service's own log, and the timings.
//
// No-leak rule: until reveal() runs, nothing on screen depends on which era is winning or on
// which era an answer favors. The strip is the full catalog in a fixed order; the progress
// squares are neutral; the scoring animation treats all 12 colors identically; and the page
// never receives the answer-to-trait weights (they stay in the client service).
"use strict";

const $ = (s) => document.querySelector(s);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const KEYS = "abcde";
// Fixed, deliberately uneven block widths: an abstract timeline of the whole catalog.
const STRIP_WIDTHS = [5, 7, 4, 6, 8, 5, 6, 4, 5, 7, 6, 5];
let QUIZ = null, STATUS = null, answers = [], qi = 0, last = null;
let advancing = false;   // true during the short pause after a pick, so a double-tap can't skip a question
let running = false;

async function api(path, body) {
  const r = await fetch(path, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {});
  const j = await r.json();
  if (!r.ok) throw new Error(j.error || `request failed (${r.status})`);
  return j;
}
const esc = (t) => String(t).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const mb = (n) => (n / 1e6).toFixed(2) + " MB";
const pct = (s) => Math.round(50 * (1 + s));
const pct2 = (s) => (50 * (1 + s)).toFixed(2);
const hexOf = (ct, n) => ct.hex.slice(0, n * 2).match(/.{2}/g).join(" ");
const secs = (ms) => (ms >= 10000 ? (ms / 1000).toFixed(1) + " s" : Math.round(ms).toLocaleString() + " ms");

// Transport = time spent moving ciphertext to and from remote hardware (the compute service measures it,
// services/backends.py). A local run never moves it, so transport_ms is null and we say n/a.
function transportShort(meta) {
  return meta.transport_ms == null ? "n/a" : secs(meta.transport_ms);
}
function transportLong(meta) {
  if (meta.transport_ms == null) return "n/a: the encrypted data never left this computer.";
  const parts = [`upload ${secs(meta.upload_ms)}` + (meta.upload_bytes ? ` (${mb(meta.upload_bytes)}: the trace, your encrypted answers and the rotation keys)` : "")];
  if (meta.download_ms != null) parts.push(`download ${secs(meta.download_ms)}`);
  else if (meta.fog_wait_ms != null) parts.push(`remote run plus download ${secs(meta.fog_wait_ms)} (the transport client doesn't yet split the download out)`);
  if (meta.fog_queue_ms != null) parts.push(`job queue ${secs(meta.fog_queue_ms)}`);
  return parts.join("; ") + ".";
}

function show(id) {
  document.querySelectorAll(".screen").forEach((s) => s.classList.toggle("active", s.id === id));
  window.scrollTo({ top: 0 });
}

function buildStrip(el, stagger) {
  el.innerHTML = "";
  QUIZ.eras.forEach((e, i) => {
    const s = document.createElement("span");
    s.style.background = e.colors[0];
    s.style.flex = String(STRIP_WIDTHS[i % STRIP_WIDTHS.length]);
    if (stagger) s.style.animationDelay = `${(i * 0.12).toFixed(2)}s`;
    el.appendChild(s);
  });
}

// The compute service describes its own backend (services/backends.py); the page just renders it,
// so switching the backend (CPU, simulator, Fog) never needs a UI change.
function backendBadge(meta) {
  const b = meta.backend;
  const job = meta.fog_job ? ` Job ${esc(meta.fog_job)}.` : "";
  const check = meta.ring_check ? " Bit-for-bit check against OpenFHE: passed." : "";
  return { remote: !!b.remote, html: `Encrypted math ran on <b>${esc(b.name)}</b>. ${esc(b.detail)}${job}${check}` };
}

// Pick black or white text for the winning color, whichever has more contrast (WCAG luminance).
function inkFor(hex) {
  const c = hex.replace("#", "").match(/../g).map((x) => {
    const v = parseInt(x, 16) / 255;
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  });
  const L = 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
  return (L + 0.05) / 0.0556 >= 1.05 / (L + 0.05) ? "#111111" : "#ffffff";
}

async function init() {
  try {
    QUIZ = await api("/api/quiz");
    STATUS = await api("/api/status");
  } catch (e) {
    $("#status").className = "quiet bad";
    $("#status").textContent = `Can't reach the helper program on this computer: ${e.message}`;
    return;
  }
  buildStrip($("#strip"), false);
  buildStrip($("#divider"), false);
  buildStrip($("#scorestrip"), true);
  const ok = STATUS.compute.ok;
  $("#status").className = ok ? "quiet" : "quiet bad";
  $("#status").textContent = ok
    ? "Encryption keys were generated on this computer when the demo started. The secret key is never sent to the scoring service."
    : "The scoring service is offline right now, so the quiz can't be scored.";
  $("#start").disabled = !ok;
  $("#start").textContent = ok ? "Start" : "Scoring offline";
}

// ---------------- quiz ----------------
function renderQuestion() {
  const q = QUIZ.questions[qi], n = QUIZ.questions.length;
  const prog = $("#progress");
  prog.innerHTML = "";
  for (let i = 0; i < n; i++) {
    const b = document.createElement("span");
    if (i < answers.length && answers[i] !== undefined) b.classList.add("done");
    if (i === qi) b.classList.add("here");
    prog.appendChild(b);
  }
  $("#qnum").textContent = `${String(qi + 1).padStart(2, "0")} / ${n}`;
  $("#question").textContent = q.q;
  const box = $("#answers");
  box.innerHTML = "";
  q.options.forEach((o, i) => {
    const b = document.createElement("button");
    b.className = "ans" + (answers[qi] === i ? " picked" : "");
    b.innerHTML = `<span class="k">${KEYS[i]}</span><span></span>`;
    b.lastChild.textContent = o.t;
    b.onclick = () => pick(i);
    box.appendChild(b);
  });
  $("#back").style.visibility = qi === 0 ? "hidden" : "visible";
}

function pick(i) {
  if (advancing) return;
  advancing = true;
  answers[qi] = i;
  answers.length = qi + 1;
  document.querySelectorAll(".ans")[i].classList.add("picked");
  setTimeout(() => {
    advancing = false;
    if (qi < QUIZ.questions.length - 1) { qi++; renderQuestion(); }
    else runScoring();
  }, 220);
}

// ---------------- scoring: real steps, nothing era-specific on screen ----------------
function step(n, state, text) {
  const li = $("#s" + n);
  li.classList.remove("live", "done");
  if (state) li.classList.add(state);
  if (text !== undefined) $(`#s${n}t`).textContent = text;
}

async function runScoring() {
  if (running) return;
  running = true;
  show("scoring");
  $("#err").textContent = "";
  $("#retry").hidden = true;
  $("#reveal").disabled = true;
  $("#s1hex").textContent = "";
  $("#waitnote").textContent = "";
  [1, 2, 3].forEach((n) => step(n, null, "waiting"));
  const strip = $("#scorestrip");
  strip.classList.remove("running", "done");
  try {
    // 1. encrypt on this computer (the local helper does it; the page only sends answers to it)
    step(1, "live", "encrypting your answers…");
    const enc = await api("/api/encrypt", { answers });
    $("#s1hex").textContent = hexOf(enc.ciphertext, 96);
    step(1, "done", `encrypted in ${enc.encrypt_ms} ms: ${mb(enc.ciphertext.bytes)} of ciphertext. A real slice of it:`);
    await sleep(700);

    // 2. encrypted scoring on the scoring service; all 12 colors animate identically
    step(2, "live", "comparing your encrypted answers with all 12 eras…");
    strip.classList.add("running");
    const since = (await api("/api/server-log").catch(() => ({ total: 0 }))).total || 0;
    const t2 = Date.now();
    const slow = setInterval(() => {
      const s = Math.round((Date.now() - t2) / 1000);
      if (s >= 5) $("#waitnote").textContent = `Still working (${s} s). Remote hardware can queue before it runs; the scoring service only has your encrypted answers.`;
    }, 1000);
    let comp;
    try {
      comp = await api("/api/compute", { job: enc.job });
      await sleep(Math.max(0, 1600 - (Date.now() - t2)));   // let the sweep be seen even on a fast local run
    } finally {
      clearInterval(slow);
      $("#waitnote").textContent = "";
      strip.classList.remove("running");
    }
    strip.classList.add("done");
    step(2, "done", `all 12 scored in ${comp.meta.server_ms} ms, still encrypted (transport ${transportShort(comp.meta)})`);
    const log = await api("/api/server-log").catch(() => ({ lines: [], first: 0 }));
    const lines = log.lines.filter((_, k) => (log.first || 0) + k > since);
    await sleep(500);

    // 3. decrypt on this computer (kept in memory; nothing is drawn until the reveal)
    step(3, "live", "unlocking with the secret key…");
    const dec = await api("/api/decrypt", { job: enc.job });
    step(3, "done", `unlocked on this computer in ${dec.decrypt_ms} ms`);
    last = { enc, comp, dec, lines };
    $("#reveal").disabled = false;
    $("#reveal").focus({ preventScroll: true });
  } catch (e) {
    $("#err").textContent = "Something went wrong: " + e.message;
    $("#retry").hidden = false;
  } finally {
    running = false;
  }
}

// ---------------- the reveal: the first moment anything era-specific is drawn ----------------
function reveal() {
  const { enc, comp, dec, lines } = last;
  const e = QUIZ.eras[dec.best];
  const root = document.documentElement.style;
  root.setProperty("--era", e.colors[0]);
  root.setProperty("--era-ink", inkFor(e.colors[0]));

  const name = $("#eraname");
  name.textContent = e.name;
  name.classList.toggle("long", e.name.length > 12);
  $("#blurb").textContent = e.blurb;
  const [top, second, third] = dec.ranked;
  const photo = pct(dec.scores[top]) === pct(dec.scores[second]);   // looks like a tie at whole percents
  $("#runners").textContent =
    `Runner-up: ${QUIZ.eras[second].name} (${photo ? pct2(dec.scores[second]) : pct(dec.scores[second])}%). ` +
    `Also close: ${QUIZ.eras[third].name} (${pct(dec.scores[third])}%).`;
  $("#photo").textContent = photo
    ? `Photo finish: ${e.name} ${pct2(dec.scores[top])}% just beat ${QUIZ.eras[second].name} ${pct2(dec.scores[second])}%.`
    : "";

  // all 12 eras, ranked
  const bars = $("#bars");
  bars.innerHTML = "";
  dec.ranked.forEach((i, rank) => {
    const s = dec.scores[i];
    const row = document.createElement("div");
    row.className = "brow" + (i === dec.best ? " top" : "");
    const shown = photo && rank < 2 ? pct2(s) : pct(s);
    row.innerHTML = `<span class="name"></span><span class="bar"><i></i></span><span class="pct">${shown}%</span>`;
    row.querySelector(".name").textContent = QUIZ.eras[i].name;
    row.querySelector("i").style.background = QUIZ.eras[i].colors[0];
    bars.appendChild(row);
    requestAnimationFrame(() => setTimeout(() => (row.querySelector("i").style.width = pct(s) + "%"), 80 + rank * 40));
  });

  renderProof(enc, comp, dec, lines);
  show("result");
}

function renderProof(enc, comp, dec, lines) {
  const tb = $("#traits");
  tb.innerHTML = "";
  QUIZ.traits.forEach((t) => {
    const v = enc.traits[t.id];
    const d = document.createElement("div");
    d.className = "trait";
    d.innerHTML = `<span></span><div class="track"><i class="fill"></i></div><span class="v">${v >= 0 ? "+" : ""}${v.toFixed(2)}</span><div class="ends"><span></span><span></span></div>`;
    d.firstChild.textContent = t.label;
    d.querySelector(".ends").firstChild.textContent = t.low;
    d.querySelector(".ends").lastChild.textContent = t.high;
    const f = d.querySelector(".fill");
    f.style.left = (v >= 0 ? 50 : 50 + v * 50) + "%";
    f.style.width = Math.abs(v) * 50 + "%";
    tb.appendChild(d);
  });

  const up = enc.ciphertext, down = comp.ciphertext;
  $("#upcap").textContent = "what was sent to the scoring service (a real slice of the ciphertext):";
  $("#uphex").textContent = hexOf(up, 384);
  $("#upmeta").innerHTML = `<span>${mb(up.bytes)}</span><span>sha256 ${up.sha256.slice(0, 16)}…</span><a href="/api/ciphertext/${enc.job}/query">download all of it</a>`;

  const b = backendBadge(comp.meta);
  $("#badge").innerHTML = b.html;
  $("#badge").className = b.remote ? "badge-remote" : "";
  $("#serverlog").textContent = lines.length ? lines.join("\n") : "(log unavailable)";
  $("#downhex").textContent = hexOf(down, 192);
  $("#downmeta").innerHTML = `<span>${mb(down.bytes)}</span><span>server time ${comp.meta.server_ms} ms</span><span>transport ${esc(transportShort(comp.meta))}</span><a href="/api/ciphertext/${enc.job}/result">download all of it</a>`;

  $("#unlock").textContent = `The local helper on this computer unlocked all 12 scores with the secret key in ${dec.decrypt_ms} ms and picked the highest one itself. ` +
    "The scoring service only ever received encrypted data, never your answers, your scores, or your era.";

  const k = STATUS.keys, ring = k.ring_dim;
  const rows = [
    ["Scheme", "CKKS, OpenFHE (Niobium's instrumented build)"],
    ["Ring dimension", `${ring.toLocaleString()}${ring === 65536 ? " (2^16, the size Niobium documents for the Fog)" : ""}`],
    ["Slots", `${k.slots.toLocaleString()} available, 96 used (12 eras × 8 traits)`],
    ["Security", ring === 65536 ? "128-bit classical, enforced by OpenFHE" : "not enforced (small test ring)"],
    ["Circuit", "1 plaintext × ciphertext multiply, 3 rotations, depth 1, no bootstrapping"],
    ["Sent to the scoring service once", `crypto context (cc.bin, ${(k.sizes["cc.bin"] / 1e3).toFixed(1)} KB) and rotation keys (rk.bin, ${mb(k.sizes["rk.bin"])})`],
    ["Sent per quiz", `your encrypted answers (${mb(enc.ciphertext.bytes)}). The encrypted scores come back (${mb(comp.ciphertext.bytes)}).`],
    ["Secret key", `${mb(k.sk_bytes)}, kept by the local helper (owner-only file); never sent to the scoring service`],
    ["Key lifetime", "one key pair, generated when the demo started and shared by every quiz until it restarts"],
    ["Where the math ran", `${comp.meta.backend.name}. ${comp.meta.backend.detail}`],
    ["Timing", `scoring service ${comp.meta.server_ms.toLocaleString()} ms end to end` +
      (comp.meta.replay_ms != null ? `, of which the recorded circuit's replay took ${secs(comp.meta.replay_ms)}` : "") +
      `; encrypt ${enc.encrypt_ms} ms and decrypt ${dec.decrypt_ms} ms on this computer`],
    ["Transport", transportLong(comp.meta)],
    ["Result size", `${mb(comp.ciphertext.bytes)}${comp.meta.towers_out ? `, compressed to ${comp.meta.towers_out} RNS tower${comp.meta.towers_out === 1 ? "" : "s"} before it was sent back` : ""}`],
    ["Scoring service", STATUS.compute_url],
    ["Decryption precision", dec.precision_bits ? `about ${Math.round(dec.precision_bits)} bits` : "n/a"],
  ];
  $("#tech").innerHTML = "<dl>" + rows.map(([a, v]) => `<dt>${esc(a)}</dt><dd>${esc(v)}</dd>`).join("") + "</dl>" +
    `<p>The trusted client is a small helper program on this computer (${esc(location.host)}), not this web page. The page sends it your answers over this computer's internal loopback connection; the helper makes the keys, keeps the secret key, encrypts and decrypts. ` +
    "In this local demo the scoring service is a separate program on the same computer. They're kept apart by design, not by the operating system: the scoring service only receives the files above, and it refuses to run if a file named sk.bin appears in its folder.</p>";
}

function restart() {
  const root = document.documentElement.style;
  root.removeProperty("--era");
  root.removeProperty("--era-ink");
  answers = []; qi = 0; last = null;
  renderQuestion();
  show("quiz");
}

$("#start").onclick = restart;
$("#back").onclick = () => { if (qi > 0 && !advancing) { qi--; renderQuestion(); } };
$("#reveal").onclick = reveal;
$("#retry").onclick = () => runScoring();
$("#again").onclick = restart;
document.addEventListener("keydown", (ev) => {
  if (!$("#quiz").classList.contains("active") || ev.metaKey || ev.ctrlKey || ev.altKey) return;
  const k = ev.key.toLowerCase();
  const i = KEYS.includes(k) ? KEYS.indexOf(k) : "12345".indexOf(k);
  if (i >= 0 && i < QUIZ.questions[qi].options.length) pick(i);
  else if (ev.key === "Backspace" || ev.key === "ArrowLeft") $("#back").click();
});
init();
